### ISSUE TITLE
Compatiblity with django-auth-ldap?

### ISSUE THREAD

**Issue by joewesch** [jazzband/django-axes#1026]
Hello, I am inquiring to see if there has been any testing for compatibility with the [django-auth-ldap](https://django-auth-ldap.readthedocs.io/en/latest/index.html) library. I didn't see it in the [Integration documentation](https://django-axes.readthedocs.io/en/latest/6_integration.html). Has anyone tested this yet?

**Comment by aleksihakli** [comment]
Hey!

In principle the package should be compatible if the `django-auth-ldap` authentication backend but it would be nice if you test it and confirm back.

In practice you can try to log in N times where N >= failure limit and check what happens.
