### ISSUE TITLE
Make the `django_ipware` an optional dependency

### ISSUE THREAD

**Issue by hirotasoshu** [jazzband/django-axes#1038]
Discussed in #1021

**Comment by aleksihakli** [comment]
Thanks for opening 👍 I made a prerelease for `6.0.0` marked as `6.0.0b1` to PyPI that we can test this in when implemented.

**Comment by aleksihakli** [comment]
I sketched out one option for the optional deps pattern so that we have some basis for further discussion, would appreciate if you can check and highlight any issues or faults you detect in it. All improvement ideas are welcome :)

**Comment by aleksihakli** [comment]
Well after some pondering the default idea in ipware, too, seems to be to just use `request.META["REMOTE_ADDR"]` if nothing better is configured and available, and for ease-of-use I'd assume that defaulting to that if we make `django-ipware` optional would be a good option? I changed the PR draft to use that approach, do check if it seems OK.

**Comment by aleksihakli** [comment]
This has been implemented and published in the prerelease version 6.0.0b2 to enable feature testing.
