### ISSUE TITLE
axes_accessattempt.username IS NULL error on postgres

### ISSUE THREAD

**Issue by seperman** [jazzband/django-axes#106]
Hello,

From time to time I get the following error:

```
function host(character) does not exist
LINE 1: ...HERE ("axes_accessattempt"."username" IS NULL AND HOST("axes...
                                                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

And emptying the 2 axes tables does not solve it. I digged into Django code and the SQL query seems fine so this might be a Postgres bug. But it is very annoying. The only way it works again for me is to delete the 2 axes tables and then recreate them. Anybody else having the same issue?

PostgreSQL 9.3.5 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit

Thanks,
Eras

**Comment by Remiz** [comment]
I was trying to experiment with postgresql and I noticed the exact same issue... I don't have it with any other app... Are you sure it's a posgres  bug?

**Comment by seperman** [comment]
Yeah I opened a bug ticket for it:
http://www.postgresql.org/message-id/20141023000528.2664.22060@wrigleys.postgresql.org
If you install updates for your postgres, it should work though. But sometimes the bug gets reintroduced to the newer versions of postgres.
