### ISSUE TITLE
AXES_LOCKOUT_PARAMETERS not working as expected

### ISSUE THREAD

**Issue by Soykertje** [jazzband/django-axes#1071]
I am using Django 4.2 and django-axes 6.0.1 and it works in general but when I define:
`AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]`

and as the [documentation](https://django-axes.readthedocs.io/en/latest/4_configuration.html) says:

> if you configure AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]], axes will block clients by ip and/or username and user agent combination. See [Customizing lockout parameters](https://django-axes.readthedocs.io/en/latest/5_customization.html#customizing-lockout-parameters) for more details.

And that is the behavior that I expect but when I test it, it blocks my computer and my phone if one of them gets blocked (if I get blocked in my computer, my phone also gets blocked even if I did not make any try), which does not make sense since I'm using different `username`s while testing, and also the `user_agent` is different... The same happens with the server deployed in a hosted machine, so it's not my local implementation.

**Comment by aleksihakli** [comment]
Hey @Soykertje ! The list defines two separate sets of attributes and is probably locking up your phone if you are testing from the same IP address as on your computer? Are you using the same WiFi on your phone?

**Comment by Soykertje** [comment]
@aleksihakli 
Yeah, I use the same network for my computer and phone, but I experiment with different usernames, and each device has a distinct user_agent.

**Comment by aleksihakli** [comment]
The first IP address is defined as a separate lockout attribute. If you wish to use it in combination with username and user agent you could use e.g. 

    AXES_LOCKOUT_PARAMETERS = [["ip_address", "username", "user_agent"]]

The documentation also has a few more examples on different combinations and their meanings.

**Comment by aleksihakli** [comment]
Closing this as the configuration above should fix the issue. Please also see https://django-axes.readthedocs.io/en/latest/2_installation.html#version-6-breaking-changes-and-upgrading-from-django-axes-version-5

**Comment by Soykertje** [comment]
Thanks @aleksihakli but then this is incorrect:

> if you configure AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]], axes will block clients by ip and/or username and user agent combination. See [Customizing lockout parameters](https://django-axes.readthedocs.io/en/latest/5_customization.html#customizing-lockout-parameters) for more details.

The correct statement is that by declaring `AXES_LOCKOUT_PARAMETERS` as `["ip_address", ["username", "user_agent"]]` and `["ip_address"]`, it would essentially have the same effect since it is only blocking based on the `ip_address` and not considering the combination of `username` and `user_agent`.

**Comment by aleksihakli** [comment]
Thanks for the notes. Please feel free to open a PR to improve the language in the docs (the quote is from there), we're open to contributions!
