### ISSUE TITLE
Username is not present in admin detail pages

### ISSUE THREAD

**Issue by sevdog** [jazzband/django-axes#1073]
As of now every model-admin of this packages defines the `fieldsets` options without providing the `username` field, this causes the field to not being displayed in any "detail" page.

https://github.com/jazzband/django-axes/blob/fcdeb4ae3f11724b99da54dfa61df90abcf54f7b/axes/admin.py#L25-L29

https://github.com/jazzband/django-axes/blob/fcdeb4ae3f11724b99da54dfa61df90abcf54f7b/axes/admin.py#L63-L66

https://github.com/jazzband/django-axes/blob/fcdeb4ae3f11724b99da54dfa61df90abcf54f7b/axes/admin.py#L98-L101

This may cause miss-understanding of what is being observed by the user if the `username` field is not used in the `__str__` method of that model.

To address this it should be enough to add `username` to the first fieldset.

**Comment by aleksihakli** [comment]
Thanks for reporting @sevdog ! Would you have the opportunity of making a PR for updating the fieldsets?

**Comment by aleksihakli** [comment]
The current test suite does not seem to contain too many tests for the admin:

https://github.com/jazzband/django-axes/blob/master/tests/test_admin.py

Adding one field to the fieldsets should be fine as-is; tests would be a nice bonus for the admin views of course, but Django already tests that the stock admin views should work properly.

**Comment by aleksihakli** [comment]
Thank you @sevdog, releasing this as version 6.0.3!
