### ISSUE TITLE
axes_accessattemp and axes_accessfailurelog are not recording

### ISSUE THREAD

**Issue by CheHaoKang** [jazzband/django-axes#1088]
Hi,

If logging succeeds, `axes_accesslog` has new records but `axes_accessattempt` doesn't have new rows.
If logging fails, `axes_accessattempt` and `axes_accessfailurelog` are not recording.

Have searched the documentation but not got the clue.
https://django-axes.readthedocs.io/en/latest/3_usage.html

Thanks.

**Comment by aleksihakli** [comment]
Hey @CheHaoKang, thanks for reporting. If you have any additional information it would be valuable for debugging this.

**Comment by aleksihakli** [comment]
As there's no further information I'm closing the issue, please feel free to get back to us for reopening.
