### ISSUE TITLE
FEATURE REQUEST: Logging without sensitive data by default (privacy by design)

### ISSUE THREAD

**Issue by GitRon** [jazzband/django-axes#1093]
Hi @aleksihakli 

we found out that AXES logs IP and username to the configured Django log on a failed attempt. The IP address is critical by definition but the username is very often the email address of the user - so it's even more critical.

I would love to see a solution where we avoid logging any sensitive information - unless you explicitly want this and enable it.

So my suggestion:
* `AXES_VERBOSE` is set to `False` by default
* The `get_client_str` method does not print the username when verbose mode is off but the User ID. This will help you as much as the username to find the specific user but you avoid spilling the data everywhere (like some fancy server or cloud logs)

What do you think? Would you be open for a PR?

Best  
Ronny

**Comment by aleksihakli** [comment]
Sure thing, like I said in #438 if you have an idea for the improvement we're always open for PRs.

**Comment by aleksihakli** [comment]
Thanks for the PR👍

**Comment by GitRon** [comment]
Thx for merging!
