### ISSUE TITLE
Check and/or fix RTD PDF build

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#1102]
RTD PDF build seems to be an old version, namely 6.0.5.x when it should be 6.1.0.x:

https://django-axes.readthedocs.io/_/downloads/en/latest/pdf/

<img width="1002" alt="image" src="https://github.com/jazzband/django-axes/assets/2477934/4382ceac-48f3-4517-9da1-8ad2323d3d95">

When comparing to the actual docs version or epub:

https://django-axes.readthedocs.io/en/latest/
https://django-axes.readthedocs.io/_/downloads/en/latest/epub/

This could also be, in theory, due to the RTD download mirror returning an outdated version because the build was fixed on 2023-08-17.

It would be good to recheck the version later and see if the download is fixed to a later version.

Proposal: update the build configuration so a fresh PDF version is built and it matches the latest HTML and epub versions.

Note that the repository now has a RTD config file for the build settings that is used with Sphinx to build the PDF and other docs: https://github.com/jazzband/django-axes/blob/master/.readthedocs.yaml

**Comment by mastacheata** [comment]
Looks like a caching/delayed build problem to me. When I download the `latest` PDF version, I get the correct release specification `Release 6.1.1.dev11+g976399e`
![Title Page of the RTD PDF](https://github.com/jazzband/django-axes/assets/716261/d7d8ab14-c926-4c1e-a17c-ce8f62fa04b7)

**Comment by GitRon** [comment]
The RTD site was cached as well. So I guess it's plausible.

**Comment by aleksihakli** [comment]
Great, I'll close this since we're up to date.
