### ISSUE TITLE
BUG: Middleware Support for Async Required to Adhere to Django’s Asynchronous Standards

### ISSUE THREAD

**Issue by krystofbe** [jazzband/django-axes#1123]
**Describe the bug** 

When using django-axes version 6.1.1, I encountered a warning related to async adaptation. According to Django's documentation on async safety (link: [Async Safety](https://docs.djangoproject.com/en/4.2/topics/async/#async-safety)), middleware can be built to support both sync and async contexts. Unfortunately, when using django-axes, I received the following warning: "Asynchronous handler adapted for middleware axes.middleware.AxesMiddleware." This indicates that the middleware is not natively supporting async contexts, which is not in line with the best practices outlined in Django's documentation.

**To Reproduce** 

1.  Install django-axes version 6.1.1 on a project running with Django supporting async features.
2.  Enable debug logging for the django.request logger.
3.  Make a request to the application.
4.  Observe the warning message indicating that the asynchronous handler was adapted for middleware axes.middleware.AxesMiddleware.

**Expected behavior** 

The expected behavior is that django-axes middleware should natively support async contexts to comply with Django's async safety guidelines. There should be no warning messages about the asynchronous handler being adapted for the middleware, ensuring optimal performance and compatibility in async environments.

**Environment**

-   Python version: 3.11.0
-   Django version: 4.2.4
-   Django-axes version: 6.1.1
-   Operating system: Mac OS X 13.5.1

**Additional context** 

The lack of native async support could potentially lead to performance issues and unexpected behaviors when the application is operating in async mode. Adhering to Django's recommendations for async safety is crucial to ensure that the middleware performs optimally and is fully compatible with Django's async features.

**Comment by aleksihakli** [comment]
Hey! We're open to pull requests so if someone has the opportunity to look into & implement the async support in the middleware and possible other necessary layers it'd be great.

**Comment by aleksihakli** [comment]
This has been fixed with help from @Taikono-Himazin in version 6.3.0, thank you both for the bug report and the fix!
