### ISSUE TITLE
Deprecated: Django-ipware is no longer maintained; move to python-ipware

### ISSUE THREAD

**Issue by RobKuipers** [jazzband/django-axes#1129]
Quote:
`This package is no longer maintained. Please use [python-ipware](https://github.com/un33k/python-ipware) instead.

python-ipware is a newer package, with more advanced features. While this a Django specific package, python-ipware can be used with Django, Flask, etc.

While this package is no longer maintained, it will continue to work as is. If you are using this package, you are encouraged to migrate to python-ipware as soon as possible.`

**Comment by aleksihakli** [comment]
Good note. Is somebody interested in opening a PR?

**Comment by RobKuipers** [comment]
The author of django-ipware has [removed the deprecated-status](https://github.com/un33k/django-ipware/commit/a14a433804f6a2826cb2e686a289caeb95e5634d) in the latest version.
Sorry for any confusion. Issue closed.

**Comment by Rooni** [comment]
I would still consider `django-ipware` deprecated since it contains a bug they don't plan on fixing. The bug is fixed on `python-ipware` however.

https://github.com/un33k/django-ipware/issues/103

**Comment by aleksihakli** [comment]
Please do feel free to open a PR for this with the necessary migration steps.

**Comment by Rooni** [comment]
It seems the issue I made on `django-ipware` set something in motion. A `6.0.0` has been released that makes `django-ipware` use `python-ipware`. So I suppose updating would be the quicker solution.

**Comment by Taikono-Himazin** [comment]
Isn't this an issue that should be closed?

**Comment by aleksihakli** [comment]
Closing as per comments; please open a new issue if you still think this is relevant.
