### ISSUE TITLE
migrations not reversible

### ISSUE THREAD

**Issue by kostrom** [jazzband/django-axes#1191]
During a deployment roll-back, we encountered an irreversible operation exception from django-axes. I had to --fake to rollback 0007

axes/migrations/0007_alter_accessattempt_unique_together.py
line 38 should be
`migrations.RunPython(deduplicate_attempts, reverse_code=migrations.reverse_code=migrations.RunPython.noop),`

The migration removes some duplicates. When rolling back, it's not necessary (or possible) to restore the duplicates, so the backwards migration should just be a noop.

**Comment by kostrom** [comment]
I tried to make a MR but permission denied to submit the branch.  
Also, I'm not sure how to run the tests. Does it expect me to configure a django project in the environment first?

**Comment by aleksihakli** [comment]
Hi @kostrom, did you get the project up and running?

You should be able to make a PR from either GitHub desktop and/or by forking the repository and opening a PR from there, those two options are probably the easiest ones.

**Comment by hirotasoshu** [comment]
@aleksihakli what do you think about adding tests for migrations? Something like [this](https://github.com/wemake-services/django-test-migrations)

**Comment by aleksihakli** [comment]
@hirotasoshu sounds great if someone can check if the migrations are backwards and forwards compatible and can set up the linter, that would be awesome!

**Comment by hirotasoshu** [comment]
> @hirotasoshu sounds great if someone can check if the migrations are backwards and forwards compatible and can set up the linter, that would be awesome!

Ok, I'm gonna make a separate issue for that, if I have a time I'll do a PR for that. For now I will just apply suggested fix by @kostrom to fix this issue ASAP

**Comment by aleksihakli** [comment]
This has been released in version 6.5.1.
