### ISSUE TITLE
Make sure header parsing is correct

### ISSUE THREAD

**Issue by IvanAnishchuk** [jazzband/django-axes#171]
Details in the inline comment https://github.com/jazzband/django-axes/commit/0239e173e00d7a1e7cc60d22d09808cd262f0f7d#commitcomment-18422665

**Comment by camilonova** [comment]
Seems like a good approach, please make a PR and tests with your desired support.

Please consider that I should not be able to send the IP address in the headers before the proxy server. Otherwise I could create a script that changes the IP address every time I make a request.

**Comment by IvanAnishchuk** [comment]
If you use nginx, you can rely on `realip` module, set a list of trusted proxies, and use `x-real-ip` header populated by `realip`.

Without a smart reverse proxy, that logic can be replicated by having a list of trusted proxies in settings, checking if remote_addr is one of them, and filtering `x-forwarded-for` and using the last entry left there instead of the first. Because the first can be supplied by a third party and hence easily spoofed.

To be clear, I'm not interested in doing anything here, axes is unfortunately unusable in my project, don't expect code from me. But its default behavior seems like too much of an error, making it susceptible to spoofing and all, so I thought I'd stop by and mention it.

**Comment by camilonova** [comment]
Could you elaborate a test script to show the error? With it someone could fix it.
