### ISSUE TITLE
illegal IP address string passed to inet_pton

### ISSUE THREAD

**Issue by samkuehn** [jazzband/django-axes#201]
Keep getting error: illegal IP address string passed to inet_pton

https://github.com/jazzband/django-axes/blob/752783fe52e456c5d7c1b14862aa83e28045e96a/axes/decorators.py#L33

Looks like you are trying to catch OSError but inet_pton in Python 2.7.12 does not raise this exception.  Python 3.5.2 raises OSError but python Python 2.7.12 does not.

I can replicate the error with the following code (Python 2.7.12)
```python
from socket import inet_pton, AF_INET6
inet_pton(AF_INET6, '67.255.125.204') 
```

**Comment by camilonova** [comment]
@samkuehn Would you like to elaborate a PR to fix it?
