### ISSUE TITLE
get() returned more than one User -- it returned 2! (Multiple None user names)

### ISSUE THREAD

**Issue by ZaberPX** [jazzband/django-axes#205]
Attempting to use axes with combination user and ip has resulted in the entire site being unreachable, every single page simply showing the plain message: `get() returned more than one User -- it returned 2!`

This is before a user has actually logged into django at all. Our system allows for multiple `None` usernames as not every user actually needs to be able to log in, while it appears axes has (admittedly fairly) assumed that there will never be more than one user with a blank username.

I haven't dug any further into this, if there is some configuration that will allow axes to work with our system then that would be wonderful.

**Comment by camilonova** [comment]
We rely on the uniqueness of `USERNAME` maybe you can try to work on a patch and see if we can support that.

**Comment by schinckel** [comment]
Hmm. It seems to me that the place where this occurs `is_user_lockable(request)` should not be executed on a `GET` request, only on a `POST` request.
