### ISSUE TITLE
As a developer I'd like to be able to disable automatic wrapping of django auth view

### ISSUE THREAD

**Issue by mvdwaeter** [jazzband/django-axes#210]
Currently the django admin automatically decorates the django auth view on ready of the Application:

https://github.com/jazzband/django-axes/blob/master/axes/apps.py

I'd like to make this optional based on a settings named e.g:
AXES_AUTO_WATCH_DJANGO_LOGIN_VIEW

This will default to True for backwards compatbility, but if False the wrapper won't be used.

In my use case I don't want to wrap the django-auth view but only a custom made login view.
The probem arrises, when both of these views use different username, password fields.

**Comment by camilonova** [comment]
I think is out of the scope of this library.
