### ISSUE TITLE
Access Logs vs. Access Attempts in Admin?

### ISSUE THREAD

**Issue by ryanprater** [jazzband/django-axes#211]
Preface: I've googled, read the docs, and read closed issues trying to find an answer to this:

Once installed, I have two models in my Django Admin: Access Logs and Access Attempts. They seem to contain similar data. My Attempts show logins that were immediately successful (0 failed logins), but my Logs sometimes capture data that my Attempts do not.

Feel free to close once answered, but it might be useful to make this clarification in the documentation as well.

**Comment by Minkey27** [comment]
AccessLog is only used to keep a log. The behavior depends on your settings. It either logs EVERY login attempt or just the failed ones. (Again depends on the settings.) You can also turn this off completely.

AccessAttempt is where the magic happens.

**Comment by ryanprater** [comment]
Thanks, closing.
