### ISSUE TITLE
Having difficulties using the White list

### ISSUE THREAD

**Issue by Daggram** [jazzband/django-axes#213]
After setting the white list to True

AXES_NEVER_LOCKOUT_WHITELIST= True

I was expecting a new option in the admin menu but that doesn't seem to be the case.

So I'm wondering in which part do I have to add the IPs that I want white listed?

I tried the documentation and it doesn't specify it at all, as well as google but couldn't find any relevant info.

Cheers.

**Comment by Minkey27** [comment]
As you can see in the source code:
https://github.com/jazzband/django-axes/blob/master/axes/decorators.py#L93
There is a function that is called to check if the given IP is in the whitelist. 

It works in combination with the following line:
https://github.com/jazzband/django-axes/blob/master/axes/decorators.py#L402

Django-axes uses different settings in the decorators.py. This is done in https://github.com/jazzband/django-axes/blob/master/axes/settings.py#L56

So put the following in your settings.py:
AXES_NEVER_LOCKOUT_WHITELIST= True
AXES_IP_WHITELIST = [
    '127.0.0.1',
]

**Comment by Daggram** [comment]
Yeah I found this a few minutes later but didn't know if I had done the right thing good to see I didn't do something horrible ahah.

Thanks this now makes more sense to me!
