### ISSUE TITLE
Allow custom activity watchers

### ISSUE THREAD

**Issue by BeOleg** [jazzband/django-axes#217]
In my app ([nexchange.co.uk](url)), I use the watch_login decorator both on the `request_sms` endpoint as well as on the `authenticate` endpoint.
The solution I came to, is to set `AXES_LOGIN_FAILURE_LIMIT` to twice as much as priorly (6 instead of 2), however if one wants to use your lib to moderate and rate limit wide range of user triggered events, the proposed solution can be better.

**Comment by camilonova** [comment]
Feel free to work on a PR, looks like a good idea.
