### ISSUE TITLE
support non-standard authentication methods

### ISSUE THREAD

**Issue by smason** [jazzband/django-axes#220]
We've been successfully using `django-axes` for a while and have recently wanted to support a REST style API as well as existing web frontend.  While writing this, I've noticed that that you check `request.is_ajax()` but I want more control than is available by default.

I'm currently doing something like:

```python
from django import http
from rest_framework.authtoken import views as base
from rest_framework.serializers import ValidationError

import axes.decorators

@axes.decorators.watch_login
def axes_watched_login(request, successful):
  if successful:
    return http.HttpResponseRedirect('/')
  return http.HttpResponseBadRequest()

class MyTokenAuth(base.ObtainAuthToken):
  def post(self, request):
    # error if currently blocked
    if axes.decorators.is_already_locked(request):
      raise ValidationError("Account Locked")

    # some dummy code to parse input and perform validation
    serializer = self.serializer_class(data=request.data)

    # push the data to Axes, so it can perform its success/failure logging
    axes_watched_login(request, serializer.is_valid())

    # handle errors for this request
    if not serializer.is_valid():
      raise ValidationError(serializer.errors)

    # more dummy code to return something to the user
    token, created = base.Token.objects.get_or_create(
        user=serializer.validated_data['user'])
    return base.Response({ 'token': token.key })
```

based on [django-rest-framework/rest_framework/authtoken/views.py](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authtoken/views.py)

As you can see I really just want some way of doing just the logging in `axes.decorators.watch_login`, which should be easy to separate.  Am happy to submit a pull request with this if you think it would be a sensible approach.

Comments appreciated!

**Comment by lorenmh** [comment]
I came here to post the same request and a similar possible solution, though I don't think you would need to pass in a 'successful' parameter:

```python
    @watch_login
    def my_login(request):
        # the code inside here is only invoked if this user isnt locked out

        if blah:
            # invalid credentials or something
            raise axes.errors.InvalidLogin(some_error_response)
        else:
            login(...)
            return some_success_response

    def watch_login(func):
        def decorated_login(request, *args, **kwargs):
            try:
                response = func(request, *args, **kwargs)
                # do all of the axes steps of logging the success, etc
                return response
            except axes.errors.InvalidLogin as e:
                # do all of the axes steps of logging the failure, etc
                return e.response
        return decorated_login


```

To me it looks like the issue with the current watch_login decorator is that it infers that there was a login error by looking at whether there was a redirect and whether the 'location' header is absent. In my custom login code I do not think that this header is set. If login failure was specified using an error / event of some kind then things would be generic enough.

Maybe there are built in Django errors for this too?

**Comment by camilonova** [comment]
You can check the new implementation using signals, should be good for you.
