### ISSUE TITLE
Always blocking the user until he solves the captcha

### ISSUE THREAD

**Issue by nasief** [jazzband/django-axes#221]
Currently, if a user tries to login for 3 times and fails to, he/she will be blocked. If he tries the fourth time with correct credentials, they will be successfully logged in.

I am trying to block a user even if he tries to login with the correct credentials and always redirect him/her to a captcha page. The `AccessAttemp` record will be deleted from the database only when the user solves the captcha. I am wondering how can this be accomplished within `axes`?

**Comment by aleksihakli** [comment]
@nasief What is your configuration with Axes? Are you using the [`@watch_login`](https://github.com/jazzband/django-axes/blob/master/axes/decorators.py#L199) decorator with login functions? 

In another project we used Axes for a 2-phase login where one login attempt was normal login and the second was MFA confirmation. Both were watched with Axes and both login views worked nicely with the decorator.
