### ISSUE TITLE
Possible issue with django 1.11

### ISSUE THREAD

**Issue by mattijevi** [jazzband/django-axes#223]
I upgraded my django install to version 1.11 and had an issue with AccessLog records not getting created on login.

My app has a signal to catch post_save creation of AccessLog:
`@receiver(post_save, sender=AccessLog, dispatch_uid="AuditEntry creation")
def access_log_creation(sender, instance, created, **kwargs):`

When I ran my tests records were not being created on login.

With django 1.10 I had my "auth" urls setup like this:
`url(r'^accounts/', include('django.contrib.auth.urls')),`

django-axes automatically decorated the login.

My current fix that appears to work is separating the login url into its own entry and decorating it like this:
`url(r'^accounts/login/?$', watch_login(login)),
url(r'^accounts/', include('django.contrib.auth.urls')),`

**Comment by mbjerkness** [comment]
+1 on this one. If django 1.11 is installed a lot of the tests fail as well.

**Comment by infaust** [comment]
+1 please :)

**Comment by pasqualguerrero** [comment]
+1 !

**Comment by grautxo** [comment]
+1

**Comment by barraquito** [comment]
+1 !!

**Comment by watollop** [comment]
+1

**Comment by jezdez** [comment]
Hi all, please refrain from leaving additional comments with "+1" as each creates email notifications to those that are watching this repo, e.g. the authors. It's rude.

**Comment by sabueso** [comment]
+1

**Comment by camilonova** [comment]
Should be fixed now.
