### ISSUE TITLE
pytz required but not installed

### ISSUE THREAD

**Issue by texnic** [jazzband/django-axes#230]
Trying to see axes tables, got 

```
ImproperlyConfigured at /admin/axes/accessattempt/
This query requires pytz, but it isn't installed.
```

and 

```
ImproperlyConfigured at /admin/axes/accesslog/
This query requires pytz, but it isn't installed.
```
Apparently, pytz is required but not installed as dependency.

**Comment by texnic** [comment]
Indeed, installing pytz manually resolved the issue.

**Comment by camilonova** [comment]
@texnic can you please add the library as a dependency on setup.py ?
Then please make a PR to solve this issue.

**Comment by texnic** [comment]
@camilonova I have never used Git or created any code changes for Github, so probably it's better if someone else does it. If nobody else can do it, I'll be happy to try, but can only do it on the weekend.

**Comment by camilonova** [comment]
I just saw on django and pytz is required https://github.com/django/django/blob/master/setup.py#L50

Please upgrade your django version.

**Comment by texnic** [comment]
1. I have Django 1.10, it is recent.
2.  It's not a valid situation anyway.
If this package requires Django 1.11, it should be in the requirements of this package.
But more correctly, this package requires pytz, so it should be in its requirements. It doesn't require Django 1.11, so that shouldn't be a requirement. If pytz is present e.g. because Django 1.11 installs it (?), then nothing will happen. If pytz is absent because Django didn't install it or the user explicitly removed it, this package should install it.

**Comment by texnic** [comment]
To avoid further lengthy discussion, I've just modified the `requirements.txt`. Apparently I can even do it online, so it was quick. Please merge #231.

**Comment by texnic** [comment]
Just found a remark in Django documentation: pytz was added as a requirement in 1.11. It was neither required nor installed in earlier versions.
