### ISSUE TITLE
Answer for locked issue: Possible issue with django 1.11 #223

### ISSUE THREAD

**Issue by iici-gli** [jazzband/django-axes#233]
in apps add following:
        #auth_views.login = watch_login(auth_views.login)
        from .admin.admin import site
        site.login = watch_login(site.login)

**Comment by aleksihakli** [comment]
This has already been stated in the previous issue. Please read the discussion.

Please submit a pull request for fixing the issue or refrain from spamming issues that burden the authors unnecessarily.
