### ISSUE TITLE
Methods to check status

### ISSUE THREAD

**Issue by texnic** [jazzband/django-axes#235]
It would be great to have a method (for a view) and/or template tag to know if user is locked out. 

E.g. the lockout view is shown based on URL. It is preserved in user browser history. So a user can, even by mistake, get to that page again and again see the lockout message, which may not valid. It would be good to redirect the user, if they are not actually locked out.

**Comment by Minkey27** [comment]
There are multiple scenario's
1: You have set an custom locked_out_template. In this case the user would not get the locked out template on refresh anymore. 
2: You have set an custom url. In this case it's completely your responsibility to check if the cooldown period is over. The django-axes isn't used anymore until you go back to your login form.
3: You don't use any of the above: User get's back to the login url on refresh.

In my opinion this is not really an issue.
