### ISSUE TITLE
Latest release is not marked as latest

### ISSUE THREAD

**Issue by mboelen** [jazzband/django-axes#237]
Hi django-axes team,

While adding your tool to our [Linux security tools](https://linuxsecurity.expert/security-tools/) section, I noticed that the 'latest' marked release is actually old. Several other releases followed up that particular release (1.3.6): https://github.com/jazzband/django-axes/releases/latest

Just wanted to let you know. And keep up the good work.

**Comment by camilonova** [comment]
Thank you. Fixed.

**Comment by mboelen** [comment]
Thanks @camilonova - we have refreshed the data on our side and recalculated tool score. Much better :+1:
