### ISSUE TITLE
All access attempts from unregistered users are written in one record

### ISSUE THREAD

**Issue by chinskiy** [jazzband/django-axes#239]
Greetings

Settings:
Django==1.8.15
django-axes==2.3.2 with default settings.

For example: when I try to login in default django admin with non existent user I've got new record in Access attempts table with Failed Logins counter equals 1 and username=testuser1.

When I try to login with another unregistered user(testuser2 for example) I don't get new user record in Access attempts table but in record username=testuser1 I have Failed Logins counter equals 2.

**Comment by camilonova** [comment]
They will appear inside the attempt. I was thinking to update the username every time a new attempt is made, let me know if you think is better this way.

**Comment by chinskiy** [comment]
Greeting @camilonova again.
Thanks for reply

For me willl be a good feature not to save such login attemps at all.
It's my feature proposal

**Comment by camilonova** [comment]
Is better to save each attempt if you want to have good information to check.
