### ISSUE TITLE
I would like to specify user that never lock after user reach out of number of login allow

### ISSUE THREAD

**Issue by namson0482** [jazzband/django-axes#242]
Hi,

I would like to except admin user that can login unlimit and never lock after user reach out number of login allow

Thanks

**Comment by aleksihakli** [comment]
Is that really sensible? If you're getting a number of unnecessary logins you probably

- have a user that is used by multiple people who typo the password; split the account
- have a user that typos his or her password a lot; instruct them to use a better password
- have someone bruteforcing a user; they should be locked out

You can also use the lock out by combination of username and IP option.
