### ISSUE TITLE
django admin not watched

### ISSUE THREAD

**Issue by GitRon** [jazzband/django-axes#243]
Hi guys,

I use django-axes in a couple of projects and I just found out that (at least with django 1.11.4) the django admin login is not being watched. I tried axes version 2.3.3 and 2.3.2.

I tried logging in to my regular login (with "watch_login()") until i get blocked. Then I switch to /admin and I can log in or try infinite times.

I went through the docs up and down but didn't find any possibility to activate or deactivate the default watching of the django admin.

Am I missing something? In earlier time there was a specific middleware class but this seems to be gone in the current version.

Thx!
Ron

**Comment by camilonova** [comment]
Currently this is not working on django 1.11.

If you want to help please check https://github.com/jazzband/django-axes/pull/240

**Comment by GitRon** [comment]
OK thx for the inifo

**Comment by reynielramirez** [comment]
i want to know if django-axes is usefull for backend of django, i have installed django 1.5, i know is old, how i can used it in login of administration? thanks
