### ISSUE TITLE
Consider using ipaddress module to allow more flexible AXES_IP_WHITELIST ?

### ISSUE THREAD

**Issue by kedare** [jazzband/django-axes#244]
Hello.

Would it be interesting to manage IP addresses using the ipaddress modules to allow a more flexible management of the IP addresses ?

Right now as far as I know we need to set full IP addresses, there's no way to specify IPv4 or IPv6 ranges (Typically enterprises are getting /48 so and every computers have a public IP so there's no easy way to just put a list of all the IP)

This would give much more flexibility (Well all the flexibility that allows the IPv4/IPv6 addressing system)

Let me know if this is something that could be interesting, I could investigate and to a PR.
Thanks.

**Comment by camilonova** [comment]
Please do. Thanks.
