### ISSUE TITLE
security: Provide PGP signed release tarballs

### ISSUE THREAD

**Issue by JosephKiranBabu** [jazzband/django-axes#245]
We've been packaging django-axes for Debian recently at https://github.com/freedombox/django-axes-deb

The packaging is all done but for one warning. 
```
P: django-axes source: debian-watch-may-check-gpg-signature
N:
N:    This watch file does not include a means to verify the upstream tarball
N:    using cryptographic signature.
N:
N:    If upstream distributions provide such signatures, please use the
N:    pgpsigurlmangle options in this watch file's opts= to generate the URL
N:    of an upstream GPG signature. This signature is automatically downloaded
N:    and verified against a keyring stored in
N:    debian/upstream/signing-key.asc.
N:
N:    Of course, not all upstreams provide such signatures, but you could
N:    request them as a way of verifying that no third party has modified the
N:    code against their wishes after the release. Projects such as
N:    phpmyadmin, unrealircd, and proftpd have suffered from this kind of
N:    attack.
N:
N:    Refer to the uscan(1) manual page for details.
N:
N:    Severity: pedantic, Certainty: certain
N:
N:    Check: watch-file, Type: source
N:
Lintian OK
```

Please provide PGP signatures for your release tarballs to make them tamper-proof and Debian-friendly.

**Comment by camilonova** [comment]
Any ideas how to do that?

**Comment by aleksihakli** [comment]
You would need to generate PGP signing keys and use them for signing your commits. A pretty nice looking short tutorial:

https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe

GitHub already supports PGP signing so you can just add your PGP key here and to some common key pools (key servers) where people can download them from and reference them :-)

GitHub help docs (there is a lot of stuff on the bottom of the page under Further reading):

https://help.github.com/articles/generating-a-new-gpg-key/

I guess signing the tarballs will require some extra work.

**Comment by camilonova** [comment]
@aleksihakli Please do if you know how. Thanks.
