### ISSUE TITLE
User not unlocked after resetting user locks

### ISSUE THREAD

**Issue by iamshubh95** [jazzband/django-axes#246]
i am using django-axes -2.3.3 
Django-1.10.5
hosted on apache-2.2
i have following settings in my setting.py -
AXES_LOGIN_FAILURE_LIMIT=3
AXES_COOLOFF_TIME=timedelta(minutes=2)
AXES_ONLY_USER_FAILURES=True

After 3 failed login attempts, i resetted the user lock using 
python manage.py axes_reset_user user

but the lock was not removed.
When i restarted the apache server then only it was removed.
So do i need to restart apache server every time i reset or is there any other way to do it?

**Comment by aleksihakli** [comment]
Could you please include your Apache and possible caching setup? How do you handle sessions in your Django code?

**Comment by iamshubh95** [comment]
we are not using caching . for session handling we are using default django default sessions.

**Comment by rvanlaar** [comment]
We had the same problem.
Django-Axes had internal changes. Now the default seems that failures are identified by IP adres.
Behind a reverse proxy the IP address was specified as None. 

These two settings fixed it for us:
```
 AXES_BEHIND_REVERSE_PROXY = True
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
```
