### ISSUE TITLE
Trusted users concept does not work with certain settings.

### ISSUE THREAD

**Issue by Minkey27** [jazzband/django-axes#251]
As the title says, trusted users do not work anymore after 2.2.1 to 2.2.3 upgrade. This is a result of the caching system. 

Assuming AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP is False, the function `get_cache_key` does not look at username anymore. This breaks the whole concept of trusted users. As the cache keys are based on ip's only. I'm not sure if this was intended or a bug but it sure is not backwards compatible. 

is_already_locked should not look in the cache but just get user attempts instead.

**Comment by Minkey27** [comment]
If this is intended behaviour, this ticket can be closed and the change should be added to the changelogs.

**Comment by camilonova** [comment]
Please add it to the changelog
