### ISSUE TITLE
invalid input syntax for type inet (postgreSQL)

### ISSUE THREAD

**Issue by kyleabens** [jazzband/django-axes#253]
Hello,

No DataErrors are thrown when using SQLite but I am getting an **invalid input syntax for type inet** when I use postgreSQL and I was hoping you could shed some light on this one for me.  I have a simple login in page that accepts the users email and pass.  When I go to login I receive the following error:
```
invalid input syntax for type inet: "test@test.com"
LINE 1: ...ttempt" WHERE "axes_accessattempt"."ip_address" = 'test@test.com':...
```
I did a lot of google searching on this and read some other issues that were filed but I have yet to find a solution.

Any help would be greatly appreciated!
Thanks

**Comment by kyleabens** [comment]
so shortly after I submitted this issue I narrowed it down to something pretty simple.  In my views.py file I reset the users login attempts to 0 when they successfully login using
`reset(request.user.username)`
It looks like this is what's throwing the error.  Am I going about it the wrong way?

**Comment by camilonova** [comment]
Please try again with the new version and let me know if you find the same issue.
