### ISSUE TITLE
Compability with older Django and Python versions

### ISSUE THREAD

**Issue by joeribekker** [jazzband/django-axes#264]
Although I encourage dropping support for older versions of Python and Django, I find the requirement for Django-Axes to work **only** with Python 3.6 (according to CHANGES.txt) and Django 1.11 a bit extreme... specially since there are far more versions of Django that are still supported, as well as Python versions.

In my opinion, there should be at least a branch that supports these versions and get bugfixes (like #261). The project works fine with Python 3.5 so I don't see any reason not to add this version to Travis and support it.

**Comment by jezdez** [comment]
Hey @camilonova, we're aiming at supporting older versions of Django and Python as long as they are supported by one of the Django releases. Let's re-add Python 2.7 support.

**Comment by camilonova** [comment]
@joeribekker Could you help me out working on a branch adding the support? I'm aware of using some python 3 at the decorator and I'm not sure what else is needed.

Since I don't have much time to work on this I would prefer someone else to take it.

**Comment by EvaSDK** [comment]
I pushed PR #258, #259 and #260 specifically to allow easier transition from 2.3 to 3 :sob: Not everyone can jump to python 3 right away ­­­— I wish I could — as a lot of Django apps are not ready for it yet.

**Comment by pope1ni** [comment]
Thanks for restoring support for Python 2.7.

Sorry to be a pain, but we should probably also restore support for Python 3.4 with Django 2.0 and follow the supported versions of Python that Django does as the standard. Pull request incoming...

**Comment by EvaSDK** [comment]
Thanks for the quick fixes guys. Now to get through the upgrade guide :)
