### ISSUE TITLE
Consider restoring support for Python 2.7

### ISSUE THREAD

**Issue by pope1ni** [jazzband/django-axes#266]
Would you consider restoring support for Python 2.7?
Some of us are unable to upgrade to Python 3 just yet.

- Django 1.8 is the previous LTS and supported until at least April 2018.
- Django 1.10 is end-of-life December 2017.
- Django 1.11 is the current LTS and supported until at least April 2020.
- Django 2.0 drops support for Python 2.

Django 1.11 is the last version to support Python 2.7 and there is no version of django-axes that supports both of these.

**Comment by jezdez** [comment]
@pope1ni Agreed, this seems premature, Python 2.7 will be most likely maintained by distros for a foreseeable future as well.

**Comment by jezdez** [comment]
Closing in favor of #264.

**Comment by pope1ni** [comment]
Thanks @jezdez.
