### ISSUE TITLE
Outdated Documentation 

### ISSUE THREAD

**Issue by mary2spam** [jazzband/django-axes#267]
As a developer, I would like to have a documentation that is consistent with the code. In the latest update,  at least one configuration option was renamed causing compatibility problems with the documentation and previous releases.

Done Criteria:
* The documentation is revised so all the configuration settings are named correctly.
* Existing name inconsistencies are fixed and added to the change log(s).

Known inconsistencies:
* AXES_LOGIN_FAILURE_LIMIT is now called AXES_FAILURE_LIMIT

**Comment by camilonova** [comment]
@mary2spam Contributions are welcome.
