### ISSUE TITLE
Add support for Django 1.8

### ISSUE THREAD

**Issue by mbaechtold** [jazzband/django-axes#270]
According to https://www.djangoproject.com/download/ we should support Django 1.8 until April 2017 and it should be compatible with Python 2.7, ~~3.3,~~ 3.4, 3.5 (see https://docs.djangoproject.com/en/1.8/faq/install/#what-python-version-can-i-use-with-django).

As discussed in #266 and #264.

**Comment by pope1ni** [comment]
Python 3.3 can probably be excluded as that was end-of-life in September 2017.

**Comment by pope1ni** [comment]
I've had a quick look, but I think that it may not be worth restoring support for this for four months.

The main issue is that the `user_login_failed()` signal which django-axes 3.0+ now depends on doesn't accept the `request` argument until Django 1.11.

**Comment by camilonova** [comment]
I agree, lets not go that far back.
