### ISSUE TITLE
Cannot import watch_login

### ISSUE THREAD

**Issue by flexpeace** [jazzband/django-axes#272]
The command below is not working when l installed the latest package. I checked the decorator and it doesn't exist

**Comment by eschercode** [comment]
Docs need updating too if this is permanent: https://github.com/jazzband/django-axes/blob/master/docs/issues.rst

**Comment by camilonova** [comment]
Is not working like that anymore. I'll remove the file.

**Comment by eschercode** [comment]
Where's the replacement documentation that explains what replaced `watch_login` and how it works?

**Comment by flexpeace** [comment]
How does it work now? Thanks and looking forward to hear from you

**Comment by camilonova** [comment]
We are using signals https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#module-django.contrib.auth.signals

There was a different approach before since there was signals back then. Now is easier to add code on your own using the signals.

**Comment by flexpeace** [comment]
Thanks for getting back to me. I went through the log_user_login_failed method inside util which you have successfully used Django Signal. Upon several tests, l realized only the failed attempts for admin locks the website. However, l am using Django Allauth with custom user based on Django's AbstractUser.  What would be the right way to use your library? is there a signal l can use to redirect the user to the lock screen template or URL?

**Comment by JosephKiranBabu** [comment]
@camilonova This project seems to follow [semantic versioning](https://semver.org/). 

An API breaking change requires a Major version release. `watch_login` being removed is a API change which breaks the projects that depend on django-axes. This kind of change shouldn't go into a patch version like 3.0.3. This would be acceptable in 4.0 release, not 3.0.3.

https://github.com/freedombox/Plinth/issues/1154

**Comment by camilonova** [comment]
@JosephKiranBabu We removed `watch_login` when 3.0 was released.

**Comment by JosephKiranBabu** [comment]
@camilonova 
django-axes 3.0.1 had `watch_login`. It was replaced by `axes_dispatch` in django-axes 3.0.2. That makes it an API change in a patch version. 
I wouldn't have complained if the upgrade from 2.3.3 to 3.0.0 had breaking changes, since that would be expected.

**Comment by eschercode** [comment]
I've made changes to the documentation and contributed a pull request (#278). Not sure about issue reopening or contributing etiquette (ironically docs are scarce on this point), so hopefully this will make this project more accessible to people considering using it.
