### ISSUE TITLE
Remove monkey-patched LoginView methods in apps.py

### ISSUE THREAD

**Issue by JosephKiranBabu** [jazzband/django-axes#273]
In apps.py, two methods of LoginView have been monkey-patched with the decorated versions from django-axes. This makes the library methods unusable as they have been replaced with their decorated versions. This is a serious problem in django applications that do not use the vanilla django LoginView and create other LoginViews by inheriting from django LoginView.
Also, now django-axes can no longer be used with django-simple-captcha since a new LoginView with CaptchaFields cannot be created.

We had to create workarounds for this problem (https://github.com/freedombox/Plinth/pull/1155/files#diff-731aef8cc92c441d1d49eed734cb4f46) to be able to use django-simple-captcha.

This monkey-patching makes a huge assumption that users of this library never create inherited LoginViews. The documentation should be updated to let the users know how to decorate their LoginViews themselves.

**Comment by camilonova** [comment]
I had the same feeling when doing the changes but I couldn't find a better way to do it.

If you have a better implementation please send a PR.

Thanks.

**Comment by JGONGSQ** [comment]
I have the same issue. I am using the Django 1.8.16 and its not working.

**Comment by D3X** [comment]
@camilonova, @JosephKiranBabu  

I can think of two possible solutions for this issue:

1. Add a settings like `AXES_MONKEYPATCH_DJANGO_AUTH` and only patch the methods if it's `True`. 

    Pros:
    + Super-easy to do (a single `if` in `apps.py` should be enough)
    + Does not break BC

    Cons:
    - It's still monkeypatching, so it's rather dirty

2. Provide an `AxesLoginView` that inherits from `LoginView` and overrides said methods. That would require people to change the way they use `axes` now, but I like it better, because it's explicit and there's no monkeypatching. The two overridden methods could even be provided by a mixin, like this:
    ```python
    class AxesLoginMixin(object):
        @method_decorator(axes_dispatch)
        def dispatch(self, request, *args, **kwargs):
            return super(AxesLoginMixin, self).dispatch(request, *args, **kwargs)

        @meethod_decorator(axes_form_invalid)
        def form_invalid(self, form):
            return super(AxesLoginMixin, self).form_invalid(form)

    class AxesLoginView(AxesLoginMixin, LoginView):
        pass
    ```

    That way, users using custom `LoginView`s could simply add a mixin to their classes to get the desired behaviour.

    Pros:
    + No monkeypatching
    + Allows for more customisation in the future
    + Users only need to add a mixin to their custom views instead of patching two methods

    Cons:
    - Breaks BC


What do you think?

**Comment by aleksihakli** [comment]
IMO it is better to break backwards compatibility and have a clear migration & upgrade route with clean code than to continue doing horrible things.

**Comment by camilonova** [comment]
@D3X Thank you, but no thank you.

**Comment by D3X** [comment]
@camilonova Thanks for the constructive critique and lots of great arguments! </sarcasm>

You ask for better solutions, I provide you with not one, but two and you basically say "fuck you" instead of, I don't know, iterating on the idea? Saying why you don't like it?

That's not how you have a discussion with the community.

**Comment by jezdez** [comment]
@D3X Michał, your response to @camilonova is offensive and unprofessional, and frankly way out of line for this discussion. I consider it a breach of our [code of conduct](https://jazzband.co/about/conduct) and putting you on notice for it. I suggest to reconsider your words carefully and change the comment appropriately. An apology to @camilonova wouldn't hurt either.

**Comment by D3X** [comment]
@camilonova sorry if you felt offended by my comment. I overreacted.

Can you please elaborate on your response? What is it that you don't like about this solution?

**Comment by camilonova** [comment]
@D3X Gladly I didn't get the last response.

I can see it's more complicated than what we have right now. I cannot see how this improves the current situation.

I'm sorry if I can't give you a more detailed explanation on this but my time is very limited.

This is just how I see it, but is not about me (personally), I'm just a contributor.

On this current approach I think it does not add any value, so I'm closing this issue.

I'm sure a better approach would be to create a PR and let others to review it.

Thank you.

**Comment by JosephKiranBabu** [comment]
Sorry, I'm new here and not familiar with the norms of this project.
This issue has been closed without resolution. Should it be assumed that it's closed as a `won't fix`?

Maybe I wasn't clear on what the exact problem is. I wasn't merely suggesting a refactoring. This is a bug that must be fixed. I should've probably stated the problem instead of giving a suggestion.

django-axes is doing infinite redirects to `/locked` when it reaches the threshold of failed logins. (https://github.com/freedombox/Plinth/issues/1138). The workaround I mentioned above is to fix that problem from the library user's side. This should ideally be fixed in the library itself.
I see that all the tests on the project are passing. Probably there isn't a test to handle this case?

**Comment by camilonova** [comment]
@JosephKiranBabu as I mentioned earlier:

> I'm sure a better approach would be to create a PR and let others to review it.
