### ISSUE TITLE
Don't store user entered password in the access log

### ISSUE THREAD

**Issue by pckapps** [jazzband/django-axes#279]
I know a user's password should never be stored in plain text in the DB. Isn't it then also bad practice to save what the user thinks his/her password is in the db? Their real password is probably close to what they entered and I don't think this should be stored. Can this be disabled somehow?

**Comment by camilonova** [comment]
I just check again and I don't see any passwords saved, we are using a method to enforce that:

https://github.com/jazzband/django-axes/blob/master/axes/utils.py#L10

Please check your setting `AXES_PASSWORD_FORM_FIELD`

**Comment by pckapps** [comment]
Thanks, will update that setting, although I don't see it in the documentation

**Comment by camilonova** [comment]
PRs are welcome anytime
