### ISSUE TITLE
unexpected empty request object in log_user_login_failed

### ISSUE THREAD

**Issue by kakulukia** [jazzband/django-axes#284]
'NoneType' object has no attribute 'META'
/python3.6/site-packages/axes/signals.py in log_user_login_failed, line 42

or now calling the authenticate method without a request object is just deprecated, but still possible so using 3rd party libs like django-restframework-jwt you might end up with a broken signal. 

So it might be a good idea to throw an error if request is None?

So far i created a pull request https://github.com/GetBlimp/django-rest-framework-jwt/pull/409 for my problematic lib, but its kinda hard to accept it since the tests are broken now, because there is no request and i dont know how to fake it that easily.

There will be other libs out there that also dont send request as an argument.

**Comment by camilonova** [comment]
We are not using `get_ip` anymore, please try again using the latest release.

**Comment by kakulukia** [comment]
@camilonova like i said before, it has nothing todo with the git_ip implementation .. even the new version of ip_address = get_ip(request) fails because the request is None if the deprecated version of authenticate is uses. Please test it yourself. Otherwise i wouldnt have opend this ticket a second time.

**Comment by kakulukia** [comment]
i just updated the line number to not reference old code, but its still the same error.
See this passage: https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.authenticate 

Changed in Django 1.11:
The **optional** request argument was added.

**Comment by markddavidoff** [comment]
@kakulukia I recommend subclassing whatever 3rd party lib you use to add the request param as seen in the comment [here](https://django-axes.readthedocs.io/en/latest/configuration.html#authentication-backend-problems)

**Comment by markddavidoff** [comment]
@kakulukia also we currentl check `if request is None` at the top of log_user_login_failed so this is at least a handled error, closing this ticket
