### ISSUE TITLE
Release version 4.0.2

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#297]
I think we should release version 4.0.2 on GitHub, PyPI, and RTD with fixes to Python 2.7 support in #296, documentation updates in #294 and #293 and slight refactoring of the `axes.utils.reset` function in #293.

**Comment by camilonova** [comment]
I agree, please do it. Just create a commit like this https://github.com/jazzband/django-axes/commit/918f040dd71540130d790b5ee8fa1dcf70c73409 and push a tag with the version.

When is done ping me and I'll approve the release to pypi.

Thanks.

**Comment by aleksihakli** [comment]
@camilonova release of source code made in signed tag [`4.0.2`](https://github.com/jazzband/django-axes/releases/tag/4.0.2).

**Comment by camilonova** [comment]
@aleksihakli just released. Thanks.
