### ISSUE TITLE
watch_login decorator no longer available

### ISSUE THREAD

**Issue by Euphorbium** [jazzband/django-axes#298]
I am updating from `django-axes==2.3.2` to `django-axes==4.0.2`
I see that watch_login is no longer in axes.decorator. This is not mentioned in changelog. What should I use instead?

**Comment by aleksihakli** [comment]
Hey,

at the moment [`axes` monkey patches the login views](https://github.com/jazzband/django-axes/blob/master/axes/apps.py) and you just need to add `axes` to `INSTALLED_APPS` if you are using stock logins.

There is also [ongoing work](https://github.com/jazzband/django-axes/pull/277/files#diff-d5b863166ea1db38a642f49a5a7c7d8fR9) on the implementation of custom login views and mixins for supporting 3rd party authentication libraries which you can look into for inspiration.

**Comment by Euphorbium** [comment]
So custom login views are not supported at the time? Why was the old functionality removed then?

**Comment by camilonova** [comment]
It was not reliable anymore and we wanted to use the newly introduced django signals.

You can patch your own view using the `axes_dispatch` decorator.
