### ISSUE TITLE
Possible bug in signals.py?

### ISSUE THREAD

**Issue by charleswhchan** [jazzband/django-axes#299]
https://github.com/jazzband/django-axes/blob/master/axes/signals.py#L59

Should the following:
```
        for attempt in attempts:
            failures = max(failures, attempt.failures_since_start)
```

be modified to:
```
        for attempt in attempts:
            failures += attempt.failures_since_start
```

Given that settings.AXES_ONLY_USER_FAILURES maybe return multiple attempts from the same user (different path or data). Wouldn't it make sense for all failed attempts to be summed together?  🤔 💭 

Thanks!

**Comment by aleksihakli** [comment]
If correct, that would better written as:

```python
failures = sum(attempt.failures_since_start for attempt in attemps)
```

**Comment by charleswhchan** [comment]
Thanks @aleksihakli. Do you know who might be able to determine if the current behaviour is correct (or not)?

**Comment by aleksihakli** [comment]
I guess @camilonova could provide some input on the subject.

**Comment by camilonova** [comment]
I can expect the current behavior is correct since it has been like this for a long time.

If you think this will be an improvement please make a PR and update tests accordingly.

**Comment by t1user** [comment]
It doesn't seem to be correct. Users are able to make more attempts than specified in AXES_FAILURE_LIMIT

**Comment by camilonova** [comment]
Are you sure?

I can tell the tests make sure about that.

https://github.com/jazzband/django-axes/blob/master/axes/tests/test_access_attempt.py#L81

**Comment by aleksihakli** [comment]
Is it possible that the user can have multiple simultaneous access attempts going on at the same time? Can the user be attempting login with different access attempt data or from different IPs?

**Comment by charleswhchan** [comment]
> Can the user be attempting login with different access attempt data or from different IPs?

(I am not an expert in axes) If you look at [models.py](https://github.com/jazzband/django-axes/blob/master/axes/models.py), `ip_addresses` and `username` are separate fields. So if `AXES_ONLY_USER_FAILURES = True`, then there could be multiple attempts records but only the `max()` # of failure from each unique IP would be considered?

**Comment by t1user** [comment]
Cache seems to be the problem in my case (just standard django config).
Have a look a the logs below. It looks like some login attempts are not
registering or even cause the total failure count to go down
(failures_since_start in database actually  go down . Post data are
correctly added to the record.).

Any ideas why this behavior? It works fine with dummy cache.

AXES: BEGIN LOG
AXES: Using django-axes 4.0.2
AXES: blocking by username only.
AXES: New login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Creating access record.
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 2 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 2 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 3 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 3 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 3 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 4 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 4 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 4 of 5
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 5 of 5
AXES: locked out {user: 'test2@test.com', ip: '89.73.79.21', user-agent:
'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101
Firefox/58.0', path: '/login/'} after repeated login attempts.
AXES: Repeated login failure by {user: 'test2@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 5 of 5
AXES: locked out {user: 'test2@test.com', ip: '89.73.79.21', user-agent:
'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101
Firefox/58.0', path: '/login/'} after repeated login attempts.
AXES: New login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Creating access record.
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 2 of 5
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 3 of 5
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 2 of 5
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 3 of 5
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 4 of 5
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 3 of 5
AXES: Repeated login failure by {user: 'test3@test.com', ip: '89.73.79.21',
user-agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0)
Gecko/20100101 Firefox/58.0', path: '/login/'}. Count = 5 of 5
AXES: locked out {user: 'test3@test.com', ip: '89.73.79.21', user-agent:
'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101
Firefox/58.0', path: '/login/'} after repeated login attempts.

**Comment by aleksihakli** [comment]
@t1user you might be facing a different problem if you're using `LocMemCache`, please see [this documentation](https://django-axes.readthedocs.io/en/latest/configuration.html#known-configuration-problems).

@charleswhchan after reading through the source code briefly your estimate seems like a legitimate one; it could be possible that an user can attempt multiple logins from e.g. different addresses and `axes` doesn't take those into account. The `AccessAttempt` model logic doing the logging into the database wasn't trivial, however, so I think we should model some different scenarios to see how `axes` behaves in different non-trivial scenarios when the user tries to login from different IP addresses. This is definitely an issue worth spending some time on.

I'm a bit busy at the moment so I can not look into this in the upcoming weeks. It would be great if someone could lend a hand on resolving the issue.

**Comment by t1user** [comment]
Sorry for a stupid question - does it make sense to use cache here at all?
Or at least would it make sense to make its implementation optional? One
definitely wouldn't want to implement a custom cache just for the sake of
Axes (and the standard django implementation LocMemCache doesn't work here).

**Comment by charleswhchan** [comment]
@aleksihakli: Thanks for the update. 

@t1user: I would also like a option to make caching optional. (also agree, it should probably be a separate ticket)

**Comment by aleksihakli** [comment]
Please move the discussion on the caching issue to #302.
