### ISSUE TITLE
Supporting device cookies

### ISSUE THREAD

**Issue by fgaudin** [jazzband/django-axes#300]
Hi,

I'm considering my options to implement a user lockout for our company and django-axes does some of what I need. I'm leaning more toward this implementation: https://www.owasp.org/index.php/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies and from what I've read of the code, it doesn't seem to support it.

Would you be open to supporting it? In which case I'm considering forking django-axes and make PRs upstream if our own requirements can fit in the existing code without too much trouble.

**Comment by aleksihakli** [comment]
Seems like a good addition to me 👍 I'm sure we are open to incorporating better ways of doing things, just open a PR for it!

**Comment by knyghty** [comment]
Was this ever implemented? I see the issue was closed but I don't see any PR or docs for this.
