### ISSUE TITLE
Make caching optional

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#302]
Contuing the discussion in #299.

@t1user it would be OK to make the caching implementation optional and that could, in fact, make the code cleaner. 

Using `LocMemCache` should raise a warning or error on startup to prevent invalid usage.

**Comment by aleksihakli** [comment]
At the moment the caching can be disabled by using the `DummyCache` backend. The caching on the module could also be made optional with simple flags, though.

**Comment by charleswhchan** [comment]
I would like to see a flag be added to axes config to control cache behaviour 😃
