### ISSUE TITLE
"Attempt to authenticate with a custom backend failed" is logged as error, should be info?

### ISSUE THREAD

**Issue by JWvDronkelaar** [jazzband/django-axes#311]
Hi @aleksihakli,

We recently ran into a small but somewhat annoying issue. We are using django rest framework with pyjwt to authenticate from our mobile app. This means no request is available which is not a problem for django but it does trigger an error when axes tries to log the login attempt. I have linked the commit where the logging was changed from info to warning.

https://github.com/jazzband/django-axes/pull/274

While I've read the comments along the commit it remains unclear to me why it should be an error instead of info or, at most, a warning. After all nothing terrible happens, axes simply does not have enough info to log this access attempt without the request info. It would be great if this could be changed.

As a side note we would like to use Axes for login attempts from our app as well. Work on that will start shortly, its a high priority for us. If such functionality is already in the making, or you have specific idea's on how to approach it, I am all ears!

**Comment by aleksihakli** [comment]
Please open a PR for fixing the [related code](https://github.com/jazzband/django-axes/blob/b83bdad71d438390432013bacf4c6532062ffefc/axes/signals.py#L31) if you wish to change the log level :)

As a side note, you will need to customize `axes` to read the correct variables in your custom application depending on your method of authentication. Please refer to [examples](https://django-axes.readthedocs.io/en/latest/usage.html#example-usage) and source code for usage.

**Comment by JWvDronkelaar** [comment]
> Please open a PR for fixing the related code if you wish to change the log level :)

I will do that! Thanks for providing me a link to the examples, that will certainly come in handy.
