### ISSUE TITLE
LoginView.dispatch vs Authentication backend

### ISSUE THREAD

**Issue by markddavidoff** [jazzband/django-axes#313]
Hi, i'm adding a ModelAdmin subclass to my implementation of django axes where i overwrite the authenticate method with logic similar to what's in `lockout_response`. Is there a reason you've chosen the LoginView.dispatch route over offering an authentication backend? 

If not, I'd gladly write up a generic one for potential merge into this lib as i think its a pretty useful way for people who call `django.contrib.auth.authenticate` instead of using a LoginView to use django axes.  

Let me know if there is interest. And great work on this lib so far.

**Comment by camilonova** [comment]
Great idea, please work on it.

**Comment by markddavidoff** [comment]
added here https://github.com/jazzband/django-axes/pull/315
