### ISSUE TITLE
Reset login attempts on successful login

### ISSUE THREAD

**Issue by larspeyer** [jazzband/django-axes#317]
Hi @aleksihakli

We ran in to the problem that failed login attempts do not get deleted on successful user login.

Let's say a user misstypes his password from time to time but between the failed logins he logs in correctly. Like this the failed logins count up and it could happen that in the future when he fails to login he gets locked out on his first try.

We fixed this with a custom login view:

```python
class CustomLoginView(LoginView):
    def form_valid(self, form):
        valid = super().form_valid(form)
        user = form.get_user()

        if valid:
            reset(username=user.email)

        return valid
```

Would it make sense to have such a functionality as a option in `settings.py`?

**Comment by aleksihakli** [comment]
Isn't this a bit dangerous considering that one successful login from given IP will reset all records for user? That would lead to a situation where an attacker from IP `A` could try to log in repeatedly, and when user from IP `B` logs in, IP `A` attempts suddenly reset, leading to weakened security.

You could, of course, reset the attempts for user and IP combination, when this would be better :)

Please refer to the `reset` implementation https://github.com/jazzband/django-axes/blob/master/axes/utils.py#L60

@camilonova do you have input for this?

**Comment by camilonova** [comment]
I agree with you @aleksihakli

**Comment by aleksihakli** [comment]
If the reset was applied to specifically the IP user was using with `reset(username=user.email, ip=<request IP>)` this change could be fine though. You can open a PR if you want it included, but we're going to move to a custom authentication backend anyway, so the resets will probably move there, too.
