### ISSUE TITLE
Lockout by username and IP does not work with custom username

### ISSUE THREAD

**Issue by jaadus** [jazzband/django-axes#318]
`AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP` does not work if the username was modified before being sent to `authenticate`.

1. `signals.py` receives the `user_login_failed` signal, and correctly fetches the modified `username` from `credentials`.
( `username = credentials[settings.AXES_USERNAME_FORM_FIELD]` )
1. It then calls `get_user_attempts` with *only* the `request` as arguments.
1. Which leads to `_query_user_attempts` (in `attempts.py`) to *incorrectly* fetch `username` from `request` (returning the unmodified value).
( `username = request.POST.get(settings.AXES_USERNAME_FORM_FIELD, None)` )
1. 0 attempts are found because the `username` in the database is the one from `credentials`, which leads to the creation of a new attempt row with every failed login, instead of incrementing the tries and eventually locking out the user.

`username` should be passed through such that it properly queries attempts.

**Comment by BasAmmerlaan** [comment]
> `username` should be passed through such that it properly queries attempts.


This would also fix another problem I ran into recently, being that axes does not work with a prefixed AuthenticationForm.
The POST data contains `prefix-username`, but `credentials` received from the signal contains just `username`.
Passing the username (as set by `AXES_USERNAME_FORM_FIELD`) from the signal all the way to `_query_user_attempts` would seem like a nice fix for both these issues.

**Comment by camilonova** [comment]
PRs are welcome anytime

**Comment by jaadus** [comment]
@camilonova I opened #343 as my proposed solution for this problem.

Passing `username` through the stack as I initially proposed won't cut it, because of the decorator on `dispatch`, which hasn't gone through any form cleaning and can't infer how username is _supposed_ to look when it reaches authentication.

**Comment by pckapps** [comment]
What if an extra setting is added to indicate what is lookup field to use? Something like AXES_USERNAME_CREDENTIAL_FIELD. If this setting is not provided it will default to AXES_USERNAME_FORM_FIELD. Should also add a warning if the field is not in the credential dictionary. I can submit a pull request if this approach will be accepted?

**Comment by jaadus** [comment]
This isn't for the situation when the actual username comes in via a different field in the post body. (That situation is discussed somewhat [in the docs](https://django-axes.readthedocs.io/en/latest/usage.html#integration-with-django-allauth).)

This is for when the username that's passed in needs to be modified (usually by adding or removing some namespacing/prefixing/whatever) based on the rest of the request or environment or something client specific that axes has no way of predicting or knowing about.

**Comment by pckapps** [comment]
I understand now. The open pull request should address this issue?

**Comment by jaadus** [comment]
Closing with the merge of #343
