### ISSUE TITLE
axes is not doing anyting

### ISSUE THREAD

**Issue by Mebus** [jazzband/django-axes#321]
Hallo,

axes is not doing anything for me. Nothing in the logs, no blocking. My Django Version is 1.11. This is my login form code:

```
# -*- coding: utf-8 -*-
import logging

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _  # I18N

# [...]

def login_view(request):
    """Show a view for users to login."""
    loginfail = False
    # Initialize form.
    if request.method == 'POST':
        form = LoginFormular(request.POST)
    else:
        form = LoginFormular()
    # If form is being submitted, handle data.
    if request.method == 'POST' and form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
```
?

Do I have to change anything in my code or is it just neccessary to enable the axes app in settings.py?

Mebus

**Comment by aleksihakli** [comment]
Please read [the `axes` usage documentation](https://django-axes.readthedocs.io/en/latest/usage.html). It seems like you are not sending the correct signals or using any login view or form that is recognized by `axes`, so `axes` has no idea of what to monitor or lock out.

Why aren't you using the [stock Django login views](https://docs.djangoproject.com/en/2.0/topics/auth/default/#module-django.contrib.auth.views)? `axes` supports those. It does not seem like you need a specialized view in this case.
