### ISSUE TITLE
Update tests for the new authentication backend

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#323]
The new backend is used in the tests. There could be a specialized test case for directly testing the authenticate method and checking it raises the PermissionDenied error.

**Comment by Alig1493** [comment]
I would like to contribute if possible.

**Comment by markddavidoff** [comment]
@Alig1493 feel free to do so. open a PR with your changes when they are ready for review.thanks!

**Comment by aleksihakli** [comment]
The new test should unit test the authentication class and the methods directly, taking inspiration from Django test things.

https://github.com/jazzband/django-axes/blob/master/axes/backends.py

**Comment by Alig1493** [comment]
I see. And will the tests be in a new file. It says update so does that mean existing test cases testing the authentication AxesModelBackend class exists already? And if not will I be writing the tests in a new file or an existing one?

**Comment by camilonova** [comment]
Try a new file
