### ISSUE TITLE
"pip install django-axes" install package missing backends.py

### ISSUE THREAD

**Issue by bwapeup** [jazzband/django-axes#326]
I installed axes today using command "pip install django-axes". The package it installs in my site-packages does not contain the backends.py file. I copied the backends.py in the latest github repo but I got the following error message when I tried to connect to my admin login page:

ImportError at /admin/login/
cannot import name 'get_lockout_message'

**Comment by aleksihakli** [comment]
Hi @bwapeup, the `backends` file is not yet in the release, only in the upstream repo. We're baking a new release with some additions. Sorry for the inconvenience!

**Comment by bwapeup** [comment]
You might want to point the pip release to an earlier version or at least remove the migration files from the broken version. I had followed the steps in the docs and by the time I discovered that this app was missing the backends.py file, the migrations have been done and the tables have been created in my db.

**Comment by EvaSDK** [comment]
Looks like the release did not made it to pypi yet.

**Comment by jezdez** [comment]
@EvaSDK The release has not been reviewed by the project lead as described in the [Jazzband release docs](https://jazzband.co/about/releases). The project lead did get an automated email about the creation of the Git tag, so it's a matter of time.
