### ISSUE TITLE
Encoding error when usernames contain non-ascii characters

### ISSUE THREAD

**Issue by toabi** [jazzband/django-axes#328]
Reason: <https://github.com/jazzband/django-axes/blob/master/axes/utils.py#L38-L39>

Quickfix when using axes: Changing the Setting `AXES_VERBOSE = False`

Adding a `u`-prefix to the details string might fix this for py2 versions while keeping py3.3+ compatibility.

**Comment by aleksihakli** [comment]
Thank you for reporting the issue @toabi. I think the correct fix is to use `from __future__ import unicode_literals` in all modules where strings are defined.

**Comment by Fohlen** [comment]
Will open a PR soon.

**Comment by aleksihakli** [comment]
@toabi @Fohlen the new release is up on GitHub, you will have to wait for a while for it to go up on PyPI :)
