### ISSUE TITLE
DjangoAxesModelBackend requires calls to authenticate to pass `request`

### ISSUE THREAD

**Issue by flexpeace** [jazzband/django-axes#336]
I am getting this error DjangoAxesModelBackend requires calls to authenticate to pass `request` after following the instructions. 

Could you guys help me out?

Thanks

**Comment by aleksihakli** [comment]
`DjangoAxesModelBackend` is not a backend in this project. Are you talking about `AxesModelBackend`?

What are your Django `AUTHENTICATION_BACKENDS`?

Which version of Axes are you using?

Have you read the [related documentation](https://django-axes.readthedocs.io/en/latest/configuration.html#authentication-backend-problems)?
