### ISSUE TITLE
Auth backend is not compatible with pytest-django

### ISSUE THREAD

**Issue by sobolevn** [jazzband/django-axes#340]
Hi, I am testing out new auth backend. 

I have failed to make it work inside the existing project, because it is not compatible with `django_admin` fixture from `pytest-django`.

This line: https://github.com/pytest-dev/pytest-django/blob/8bd3d3ea058fbe337db69d8c0256b995351b4161/pytest_django/fixtures.py#L228

causes this error:

```
==================================== ERRORS ====================================
___________________ ERROR at setup of test_admin_authorized ____________________

db = None, admin_user = <User: admin>

    @pytest.fixture()
    def admin_client(db, admin_user):
        """A Django test client logged in as an admin user."""
        from django.test.client import Client
    
        client = Client()
>       client.login(username=admin_user.username, password='password')

/usr/local/lib/python3.6/site-packages/pytest_django/fixtures.py:228: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.6/site-packages/django/test/client.py:628: in login
    user = authenticate(**credentials)
/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py:70: in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py:116: in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <axes.backends.AxesModelBackend object at 0x7f185285f358>, request = None
username = 'admin', password = 'password', kwargs = {}

    def authenticate(self, request, username=None, password=None, **kwargs):
        """
            Add django-axes handling and add allow adding errors directly to a passed return_context.
            Will never actually authenticate a user, just blocks locked out uses so don't use this as your only back end.
            :param request: see ModelBackend.authenticate
            :param username: see ModelBackend.authenticate
            :param password: see ModelBackend.authenticate
            :keyword response_context: context dict that will be returned/used in the response template.
                NOTE: will overwrite 'error' field in dict
            :param kwargs: see ModelBackend.authenticate
            :raises PermissionDenied: if user is already locked out.
            :return: Nothing, but will update return_context with lockout message if user is locked out.
            """
    
        if request is None:
>           raise AxesModelBackend.RequestParameterRequired()
E           axes.backends.AxesModelBackend.RequestParameterRequired: DjangoAxesModelBackend requires calls to authenticate to pass `request`

/usr/local/lib/python3.6/site-packages/axes/backends.py:34: RequestParameterRequired

```

What to do in this case?

**Comment by aleksihakli** [comment]
Hey @sobolevn! Using the module without a request object is not feasible as it does nothing sane. Just use the normal Django model backend in your test setup, or refactor the pytest fixture to pass a request object in.

**Comment by sobolevn** [comment]
@aleksihakli thanks! But this is still not clear for me.

Things you have suggested are perfectly valid, but I would like to research this specific topic for some more.

## Scope

Actually that's not about `admin_client` at all.
That's about using django's `client`. Because it is now impossible to login any users inside tests with `'axes.backends.AxesModelBackend'` enabled.

## Solutions

### Refactoring django test client calls

`django` operates with client in a way, that there is just no `request` object available before we actually call `client.${http_method_name}`. So, it would be very hard to inject the desired `request` object into the `client.login()` method which happens **before** this request is even created.

So, we will need to mock `request` here somehow. I don't know how exactly. 
We also could try to use `RequestFactory` for this, but it is not the same at all.

### Using different settings for tests

That's not exactly a right thing to do. I would expect that my auth backend would behave 100% the same way for both testing and production.
And the change is quite big! Raising `403` is always a major thing to look for.

And I don't want to be secure in production. I want to be secure by default. That's why I use `django-axes` in the first place.

## Conclusion

I have failed to find a way to integrate `django-axes` and `django-client` together.
In my point of view, we need to update docs on how to solve this problem.

@camilonova @aleksihakli So, could you please guide me?

**Comment by aleksihakli** [comment]
The `AxesModelBackend` implements checks for logging in and interrupts the login process if it detects suspicious behaviour in the request. If the request object is not available it really can't do anything useful. The choice in axes was to either ignore the request object not being available or to

**Comment by aleksihakli** [comment]
No problem :) I, too, hope that the backend could be improved, but the internal design of Django makes it a bit difficult at the moment and would require major refactoring.

**Comment by skinderis** [comment]
@aleksihakli your provided solution doesn't work for me, because I am trying to test if user exceeded `AXES_FAILURE_LIMIT` and get `403` error. If I rewrite `AxesModelBackend` and return nothing from `authenticate` method it exceed the login attempts. 
Maybe I am doing something wrong? Thanks!
