### ISSUE TITLE
List of available major documentation versions on RTD

### ISSUE THREAD

**Issue by barseghyanartur** [jazzband/django-axes#342]
Please, do.

**Comment by camilonova** [comment]
PRs are welcome anytime

**Comment by barseghyanartur** [comment]
@camilonova:

That (documentation made available for all major versions) should be done from RDT management interface. 

There's no pull request possible to solve that. 

You could, however, grant me access to RDT of django-axes. Just in case, my RDT username is `delusionalinsanity`.
