### ISSUE TITLE
Do we ever actually set the AccessAttempt.trusted flag?

### ISSUE THREAD

**Issue by markddavidoff** [jazzband/django-axes#344]
We check it in lots of places but I don't se it actually being set anywhere. Can someone point me to a place where we do that? I expected it in `signals.log_user_logged_in` but that's only `AccessLog.trusted`

**Comment by camilonova** [comment]
I think we should remove it.

**Comment by aleksihakli** [comment]
New patch that removes the flag is in the `development` branch and will be part of the new major release after 4.5.0.
