### ISSUE TITLE
ImportError: cannot import name watch_login error for django-axes==4.0.1

### ISSUE THREAD

**Issue by poojaamd** [jazzband/django-axes#346]
Hi There, 

I am working towards upgrading django to django-1.11. And when i upgrade to django-axes==4.0.1. I am getting the following error:

from axes.decorators import watch_login
ImportError: cannot import name watch_login

I use the watch_login decorator around my backend module which handles login. How does one enable watch_login with 4.0.1 axes version ?

Thank you for your help.

**Comment by aleksihakli** [comment]
Hey poojaamd, the decorator is not available in version 4.0.1:

https://github.com/jazzband/django-axes/blob/4.0.1/axes/decorators.py

You don't need to import it.

**Comment by poojaamd** [comment]
@aleksihakli : Thank you for the comment. What is the alternative ? i-e how do i integrate watch_login like functionality ?

**Comment by aleksihakli** [comment]
Hey poojaamd, you should be able to use `@axes_dispatch`. 

Just make sure your application correctly sends the following Django signals:

```
from django.contrib.auth.signals import user_logged_in
from django.contrib.auth.signals import user_logged_out
from django.contrib.auth.signals import user_login_failed
```

You can check out the source code to view the correct functionality. 

You should probably use a newer version of axes, 4.4.0 is available:

https://pypi.org/project/django-axes/
