### ISSUE TITLE
Can I modify some axes configurations at runtime?

### ISSUE THREAD

**Issue by TuanDang1509** [jazzband/django-axes#347]
As requirement from user, we want a page that I can custom some login configuration as : login attemp fail, cool off, lock out ... 
I found on your document: These should be defined in your settings.py file. >> Mean I can setting some place not settings only?

**Comment by aleksihakli** [comment]
The settings should not be customized during runtime and the current codebase doesn't support it.

You can fork axes and modify it to do the things you want since it is open source
