### ISSUE TITLE
axes_dispatch is not tracking login attempts

### ISSUE THREAD

**Issue by skinderis** [jazzband/django-axes#351]
I am trying to add decorator `axes_dispatch` to my view function without class. But it it is not locking out if `settings.AXES_FAILURE_LIMIT` is achieved. 

login attempt:
`res = self.client.post(url, data=payload)`

urls.py
```
path('authenticate/', views.user_get_or_create,
         name='accounts.user_get_or_create')
```

Custom view:
```
@csrf_exempt
@not_logged_in_required
@axes_dispatch
def user_get_or_create(request):
...
```

How I can decorate function using `axes_dispatch` decorator?

**Comment by aleksihakli** [comment]
Are you sending the correct signals on login failures? Please refer to the source code of the [decorators](https://github.com/jazzband/django-axes/blob/master/axes/decorators.py) and the [signals](https://github.com/jazzband/django-axes/blob/master/axes/signals.py).

**Comment by skinderis** [comment]
@aleksihakli What is the signal or configuration to lockout not only if AXES_FAILURE_LIMIT is exceeded? Because, as I see if call user_logged_in() signal it is not locking out user who is logs in too many times. I use django axes for sms_sent function, so I want to lock user if he tries to send_sms too many times.
 Thanks!

**Comment by markddavidoff** [comment]
@skinderis you cannot log out a user for logging in too many times. That is not what axes is for. you can manually trigger the `user_login_failed` and `user_logged_in` signals, but i recommend against re-inventing the wheel for security and recommend you call `django.contrib.auth.authenticate` and let it handle all of that for you. If you have the authentication backend setup this should settle this all.

Closing as this is not a standard axes use case.
