### ISSUE TITLE
Log in attempts are not consecutive

### ISSUE THREAD

**Issue by tadamra** [jazzband/django-axes#352]
I am using django-axes 4.1.0. I set  The number of failed login attempts to 5 attempts to block the user. I noticed that the login attempts are not consecutive. If the user does 4 failed login attempts followed by 1 successful attempts and then 1 failing attempt, he will be blocked all the same. 

After reviewing possible configurations for django-axes I noticed that there is no possible config I could use to enforce the behaviour I need. Is there a way to force this required behaviour? If not I would regard this as an issue, because it is more  intuitive to force the attempts to be consecutive or at least make this option configurable.

**Comment by wodCZ** [comment]
Could be implemented by listening to `user_logged_in` signal and calling `reset(ip=ip)` there.

Keep in mind that this could cause security issues. Imagine that the user sits in a cafe with an attacker at the same wifi. User successfully logs in, and grants the attacker new attempts.

**Comment by sagar270690** [comment]
> """
Manages incoming connections from all communication channels and routes them to the proper channel managers
"""
Can use `reset(username=user.username)` instead.

**Comment by markddavidoff** [comment]
If you are only locking on IP, this could indeed give the attacker more attempts. If you are locking on more criteria we can reset on successful login as that would only give the attacker at most (2 x AXES_FAILURE_LIMIT) -1 attempts. Should be re-using teh _query_user_attempts logic in reset anyway IMHO...

**Comment by tadamra** [comment]
Thanks to everyone who participated in this issue. I will close it now.

**Comment by tadamra** [comment]
The issue is still there after the feature has been merged (I guess only now it could be labeled as a bug since the functionality has been implemented). I set AXES_RESET_ON_SUCCESS to True after updating the version, still the required result is not attained.

By checking the table "axes_accessattempts"  in the database I can see that the number of attempets is not reset to zero after the successful login. Actually at a successful attempt the user has to be removed from the table completely, not only set its attempts to 0, but of course it is not. 

Please contact me if anymore information is required to solve the bug.

**Comment by arjenzijlstra** [comment]
I believe this is due to the fact that the code adding the `reset_on_success` setting is not included in the most recent release.

**Comment by tadamra** [comment]
I noticed that is was added to the documentation on https://django-axes.readthedocs.io/en/latest/configuration.html

This means that it should be functional and it is added to the current version.

Anyway I will retest it in the next release, after verifying weather the feature is added or not.

**Comment by arjenzijlstra** [comment]
In that case I guess that the documentation does not match the current release. I don't know who to refer this to, but let's ping @markddavidoff for now.

**Comment by markddavidoff** [comment]
hmm i think this is a communication issue, `latest` usually points to latest development branch. `stable` would be most recent tagged release. See (Read the Docs' input on this)[https://docs.readthedocs.io/en/latest/versions.html#how-we-envision-versions-working]. If you check `stable`, the feature it shows that the feature want is not in the latest release. I don't know why read the docs chose to make `latest` the default but i think the only person who can change the RTD settings is @camilonova

**Comment by markddavidoff** [comment]
Closing this as this is a miscommunication and not actually anything to do with the issue. if you checkout the latest code directly and the issue persists, repopen. If you wish to change the docs, open another issue or pr
