### ISSUE TITLE
Blocking accounts after certain number of failed OTP attempts

### ISSUE THREAD

**Issue by Priyanka12345678910** [jazzband/django-axes#354]
I am using django-two-factor-auth. It's username/password page works fine with django-axes but I want to block accounts after certain number of failed OTP attempts also. Can anyone let me know how 
how to do this ?

**Comment by aleksihakli** [comment]
The documentation and axes source code are probably good places to start. The implementation is not too complex but it will be specific to your project. 

You have a custom need so you will have to do some R&D. I doubt people will invest their time and solve your problems for you for free.
