### ISSUE TITLE
Handling unicode characters in User-agent string

### ISSUE THREAD

**Issue by Remiz** [jazzband/django-axes#355]
It is a really minor issue but when checking my error logs I noticed errors related to django-axes when someone has unicode characters in their user-agent string (I suspect pentesters).

For instance the user-agent string `\ð\'\'\ð""` triggers a UnicodeDecodeError at this line https://github.com/jazzband/django-axes/blob/master/axes/attempts.py#L69
```
Exception Type: UnicodeDecodeError at /login/
Exception Value: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

It could be related to the fact I'm still using Python 2.7.12 tho, but having unicode support with that version would be nice.

Thanks.

**Comment by matt-hoskins** [comment]
I think that encoding the user-agent plucked from META to utf-8 is probably the wrong thing to do anyway - while the request.META header values will be native strings (and those will be unicode native strings under python3) they will not have been decoded via any sort of encoding (see PEP-3333). 

The following may make more sense instead as a way of handling them as you just need a reliable way to ensure they're in a byte string for hashing:
ua = ua if isinstance(ua, bytes) else (ua or '').encode('latin-1')

**Comment by matt-hoskins** [comment]
Hmm, although having tried the change I mentioned above you then run until problems elsewhere under python 2.7 where request.META.get('HTTP_USER_AGENT') is a str that's not utf-8 encoded - the attempts to create access attempt instances etc will get upset. Under python3 it's not an issue as they're just unicode strings. I think the only way to make it handle (under python 2.7) where nefarious people could stick any old junk in the user-agent header would be to have a get_user_agent function, used in place of request.META.get('HTTP_USER_AGENT'), which would fetch request.META.get('HTTP_USER_AGENT') and if the result is an instance of bytes then do .decode('latin-1') on it before returning. Wouldn't then need to change the line in attempts.py that encodes ua to utf-8.

**Comment by camilonova** [comment]
Please use python 3
