### ISSUE TITLE
axes_reset management command ignores first IP address argument

### ISSUE THREAD

**Issue by bluelightning** [jazzband/django-axes#362]
I attempted to use the `manage.py axes_reset` command to reset a test attempt that I had made by IP address i.e.

`./manage.py axes_reset 127.0.0.1
`

This does not do anything though because the first IP address is ignored deliberately on the assumption that it is the name of the `ip` argument (see [54902242c1e194f36ecc028c0c56c9a99e61eb6a](https://github.com/jazzband/django-axes/commit/54902242c1e194f36ecc028c0c56c9a99e61eb6a)), however that does not appear to be accurate here.

**Comment by markddavidoff** [comment]
I believe its the difference between `./manage.py axes_reset 127.0.0.1` and `./manage.py axes_reset ip 127.0.0.1` lol. This is pretty unclear as the other command is actually `axes_reset_user` so you'd expect this one to be `axes_reset_ip` so we need some consistency there one way or the other.

**Comment by markddavidoff** [comment]
Marking this as a bug because what it does is not what it says it does (depending on how you read it)
