### ISSUE TITLE
Pypi release of 4.4.1 doesn't match the github release

### ISSUE THREAD

**Issue by jsharpe** [jazzband/django-axes#367]
Looks like the last minute merge of the missing migrations didn't make it into the version pushed to pypi. Could a 4.4.2 version be pushed out to pypi with this fix please?

**Comment by markddavidoff** [comment]
@aleksihakli @camilonova what tag did you release?

**Comment by markddavidoff** [comment]
guess the first tag off the branch is what got released should match now.

**Comment by aleksihakli** [comment]
Version 4.4.2 is now released in PyPI @markddavidoff.

https://pypi.org/project/django-axes/4.4.2/

**Comment by markddavidoff** [comment]
thanks @aleksihakli
