### ISSUE TITLE
Infinite loop with Django Rest Framework authentication

### ISSUE THREAD

**Issue by rayer4u** [jazzband/django-axes#373]
When use axes with rest framework, using basic authentication. app crash with "maximum recursion depth exceeded while calling a Python object".
here is the debug report
[response_1544513443445.txt](https://github.com/jazzband/django-axes/files/2670215/response_1544513443445.txt)

from 
```
File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in initial
  400.         self.perform_authentication(request)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in perform_authentication
  326.         request.user
```
to 
```
File "/usr/local/lib/python3.6/site-packages/axes/attempts.py" in is_user_lockable
  159.     if hasattr(request.user, 'nolockout'):
```
pip info 
[1.txt](https://github.com/jazzband/django-axes/files/2670232/1.txt)

**Comment by markddavidoff** [comment]
@rayer4u What version of DRF are you using and are what method of  authentication? There is a case where the request DRF passed to authenticate() is actually DRF's Request() class which itself calls authenicate and not WSGIRequest causing an infinite loop. If this is the case you have I know a workaround but the bigger fix involves a bigger change to axes to not rely on request.

**Comment by rayer4u** [comment]
Thanks for reply. I use djangorestframework=3.90, django-axes=4.43, base authentication. I follow the code, DRF now use request wrapper and override request.user as you say. Maybe writing a auth backend is different between DRF and django. @@

**Comment by markddavidoff** [comment]
Here is a workaround I've been using:
https://gist.github.com/markddavidoff/4156b8072e587b77e639269fbfac3b0f

**Comment by markddavidoff** [comment]
I think this is a bug in DRF that needs to be fixed but would also be fixed if we stopped relying on request. There is a workaround, but I'd like to keep the issue open for visibility.

**Comment by camilonova** [comment]
@rayer4u can you check if the version 4.5.1 fixes this problem?

**Comment by markddavidoff** [comment]
if we're calling request.user the issue will still happen, They've rejected my pr, but the DRF folks always need an inane amount of convincing that they actually have a bug, so if anyone has time to build drf tests prooving the issue, you can take up the pr. I'm swamped this year with other obligations already unforutunatley

**Comment by camilonova** [comment]
We are not calling anymore to `request.user` so is very likely this issue is not happening anymore. I was fixed for me, but I would like to have another confirmation to close this issue.

**Comment by camilonova** [comment]
I'll mark this as fixed
