### ISSUE TITLE
Django 2.1 LTS support

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#374]
At the moment Django 2.1 tests don't work. As it is the LTS version it would be very valuable to investigate why the tests fail against the admin views and how they could be fixed.

**Comment by markddavidoff** [comment]
My opinion is to abandon the admin views altogether in favor of the authentication backend approach

**Comment by aleksihakli** [comment]
@markddavidoff Yeah, I think that is the correct and neater approach here. Depending on an application that can change (even if it does so rarely) is really not good practice. 

We should be testing against the authentication backend on the unit level and then make integration tests that verify the authentication backend behaves correctly when plugged in with user applications and other 3rd party applications like DRF.
