### ISSUE TITLE
Use signals and authentication backend for attempt monitoring and lockouts

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#389]
Implement the user login attempt monitoring and lockouts as an authentication backend instead of using the current approach of decorating all the views the user might use. 

Listen for signals for user login and logout events for attempt tracking.

Implement the authentication backend as an reusable and customisable class that users of this package can specialize to fit their own needs.

Possibly refactor the current APIs to wrap the request and credentials as discussed in https://github.com/jazzband/django-axes/pull/377 and make the requests and credentials resolver pluggable and extensible as well.

Design and document the authentication APIs so that they have clear entrypoints and expected return values and are easy to customize and extend.

**Comment by nasirhjafri** [comment]
Hi @aleksihakli Can I work on this one?

**Comment by camilonova** [comment]
@nasirhjafri Sure, go ahead.

**Comment by aleksihakli** [comment]
@nasirhjafri the project is open for anyone to contribute and it would be nice to have more people onboard for improving the package so go ahead!
