### ISSUE TITLE
Python 2.7 support ends on 2020-01-01

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#395]
As Python 2.7 EOL is closing in I am opening this ticket to remind everybody to upgrade their Python 2.7 Django projects to a supported Python 3 version.

This package will be dropping support for Python 2.7 on 2020-01-01 and removing support from the CI test matrix, file encodings, old packages and so forth, effectively declaring Python 2.7 untested and unsecure in favor of speeding up development in Python 3.5+ for this package.

https://pythonclock.org/

**Comment by camilonova** [comment]
Oh yeah, lets remove all python 2.x support and move forward.

**Comment by aleksihakli** [comment]
I'm considering starting a new Python 3 only branch for the version 5.0 release to facilitate cleaning up the codebase from Python 2.x and 3.4 support ahead of time since we can drop both of those, cleaning up requirements and packages as well. 

A new major release and development branch would also offer possibilities for cleaning up the management commands and bugs since changing those require breaking backwards compatibility.
