### ISSUE TITLE
IntegrityError at /user/login null value in column "trusted" violates not-null constraint

### ISSUE THREAD

**Issue by nedamoeini1370** [jazzband/django-axes#419]
I give above error when username or password is not correct.
i don`t have this issue in localhost but in test server i give this error. i use nginx and uwsgi to setup django application.(nginx configuration has been check)

**Comment by aleksihakli** [comment]
Hi @nedamoeini1370! Which version of Axes are you using? Have you run all the migrations with `python manage.py migrate`?

**Comment by nedamoeini1370** [comment]
Hi @aleksihakli ,
 Thank you for your prompt reply. 
1- Django version: 1, 11, 20, final
2- Django-axes version: 4.5.4
3- Yes, i apply all migration. (local database and test environment database are the same)
4- 
Request Method: | POST
Django Version:1.11.20
Exception Type: IntegrityError
null value in column "trusted" violates not-null constraint DETAIL:  Failing row contains (19, Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like ..., 192.168.21.165, n.m, null, text/html,application/xhtml+xml,application/xml;q=0.9,image/webp..., /user/login, 2019-03-12 08:56:52.99847+03:30, , csrfmiddlewaretoken=Dumm2ZyiBtHxdsI9PQKTtxaC723uhRXo8ApRTOFlYVpJ..., 1).

**Comment by nedamoeini1370** [comment]
My configuration: 
Settings.py:
1- Add 'axes' to INSTALLED_APPS
2- `AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]`
3- Axes configuration 
`AXES_ONLY_USER_FAILURES = True
AXES_LOCKOUT_TEMPLATE = 'axes_403_template.html'
AXES_COOLOFF_TIME = 2
AXES_FAILURE_LIMIT = 10`

4- Add "axes_dispatch" decorator to the top of the login views.

**Comment by aleksihakli** [comment]
After some digging I can't find any reason why this error would be caused but for missing migrations. The `trusted` should have a sane default value of `False` everywhere and there should be no place in the Axes code where it is set to `None` (which would be `null` in the database).

Is it possible to reinitialize the other test server database and run the `python manage.py migrate` command on the server before any data imports and see if that fixes the problem?

**Comment by aleksihakli** [comment]
Closing as no one else has reported this issue.
