### ISSUE TITLE
 You do not have 'axes.backends.AxesBackend' in your settings.AUTHENTICATION_BACKENDS.

### ISSUE THREAD

**Issue by SalahAdDin** [jazzband/django-axes#430]
Hello guys, 
I came again to `django` and i'm trying to implements this good package, but i'm getting this warning message:
` You do not have 'axes.backends.AxesBackend' in your settings.AUTHENTICATION_BACKENDS.`

The problem is, i have that setting set up in my files:
```
 (backend)  joselito92@joselito-asus-rog  ~/Proyectos/Work/erasmus/backend/erasmus  ./manage.py diffsettings 
ALLOWED_HOSTS = ['*']
AUTHENTICATION_BACKENDS = ['axes.backends.AxesModelBackend', 'django.contrib.auth.backends.ModelBackend']
```

What's happening?

**Comment by aleksihakli** [comment]
@SalahAdDin your authentication backend is `axes.backends.AxesModelBackend` instead of `axes.backends.AxesBackend`. The old `axes.backends.AxesModelBackend` has been renamed and only a backwards compatibility class is available for it.

The documentation on Read the Docs is still pending an update to version 5.0. In the meantime you can check the installation instructions in here:

https://github.com/jazzband/django-axes/blob/5.0/docs/2_installation.rst

**Comment by SalahAdDin** [comment]
I think documentation is outdated.
Thank you very much.

**Comment by aleksihakli** [comment]
@SalahAdDin the documentation has now been updated. 

There was an issue with the Read the Docs webhooks and GitHub being out of sync.

**Comment by GitRon** [comment]
Sorry to bring up old issues but I derived a custom class from `AxesBackend` and I still get this warning. 
It's a bug, right @aleksihakli ? `if 'axes.backends.AxesBackend' not in settings.AUTHENTICATION_BACKENDS` does not check for child classes.

**Comment by aleksihakli** [comment]
I'll remove the deprecation check, it's not that necessary.

**Comment by aleksihakli** [comment]
@GitRon the best solution seems to be to silence the check with the [`SILENCED_SYSTEM_CHECKS`](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SILENCED_SYSTEM_CHECKS) flag. 

Could you try setting the following configuration flag in your `settings.py` and see what it does?

```python
SILENCED_SYSTEM_CHECKS = ['axes.W003']
```

I think explicitly silencing the checks is a better approach than implicitly forgetting to add the authentication backend and possibly sporting security flaws in the project.

If this is a sound solution I'll add documentation on it and describe the check warnings that are configured for Axes.

**Comment by aleksihakli** [comment]
The docs now have a [section](https://django-axes.readthedocs.io/en/latest/2_installation.html#disabling-axes-system-checks) about disabling system checks for Axes.

**Comment by GitRon** [comment]
Really great! Thanks!
