### ISSUE TITLE
Show changelog in docs.

### ISSUE THREAD

**Issue by jezdez** [jazzband/django-axes#431]
Seems like there is a good changelog but it's not integrated into the Sphinx based docs. You could simply use the include rst directive to have it show up in a separate Sphinx document.

**Comment by aleksihakli** [comment]
Changelog has now been added to the documentation in https://github.com/jazzband/django-axes/commit/16f96de8fd8ab3e5e3103d1bb077a3af96096918 and released on Read the Docs in version 5.0.1.
