### ISSUE TITLE
Enable django-axes only for staff/admin site

### ISSUE THREAD

**Issue by csdenboer** [jazzband/django-axes#432]
I would like to only enable django-axes for staff accounts (preferably only admin site). According to the documentation this is currently not possible (I can't find anything about it). Is it true? Thanks!

**Comment by aleksihakli** [comment]
Hey! 

Axes does not yet have flags for only enabling it only for the admin site. It would be quite possible to implement this, and if you would like to have the feature, I would recommend giving it a go yourself and opening a PR. The [`request.path`](https://docs.djangoproject.com/en/2.2/ref/request-response/#django.http.HttpRequest.path) property could be one place for implementing a check in authentication backend layer. 

You can implement this in your own project as well with something like:

```python
import re

from axes.backends import AxesBackend
from axes.helpers import toggleable


class AdminBackend(AxesBackend):
    @toggleable
    def authenticate(self, request, *args, **kwargs):
        if re.match('^/admin', request.path):
            super().authenticate(request, *args, **kwargs)
```

**Comment by csdenboer** [comment]
Hi, thanks for the reply. We have chosen for an alternative solution for now (separate site only running admin). I will submit a PR in case we implement a solution thats worth merging. Thanks for all your efforts.

**Comment by aleksihakli** [comment]
Glad to hear found a solution for your site @csdenboer! 

I would like to leave this issue open, as this is a very good feature request, and others might wish to discuss about and implement this functionality.

**Comment by aleksihakli** [comment]
Resolved by PR #459.

**Comment by getup8** [comment]
@aleksihakli do you mind clarifying what the AXES_ONLY_ADMIN_SITE flag does exactly?  I've set it in my project and failed login attempts on my normal site are still recorded in the database (although I don't think lockout actually occurs).  Is that WAI?  Ideally, I'd like as little axes code as possible to be run and no database calls to be made when someone logs in to the normal site.

**Comment by hramezani** [comment]
@getup8 based on documentation

> AXES_ONLY_ADMIN_SITE : If True, lock is only enable for admin site

It means the locking just works for the admin site and failed login attempts still recorded for all requests.

**Comment by aleksihakli** [comment]
The flag allows login on other URLs than admin. On admin it checks the lockout statuses normally.

https://github.com/jazzband/django-axes/blob/ffc396050b5214ddcd1b55e05a66453c5d1e87ad/axes/handlers/base.py#L153

If you'd like to skip database calls on a normal session, you can e.g. specialize the database handler. Read the documentation for references on the handlers. The current design is so that the successful and failed logins are recorded via signals, which the handlers attach to. You can just implement a simple override that skips calling the handlers if the URL is to a normal user site.

We can't really skip recording logins in the stock implementation since the URLs aren't constant across user installations (your URLs are different than someone elses), so you'll have to do that specializing yourself.

If you figure out a reliable way for doing the checks in the base plugin, please open a PR, contributions are most welcome!

**Comment by vschettino** [comment]
I bumped at the same issue with AXES_ONLY_ADMIN_SITE, where I wanted to avoid any overhead on APIs calls and let Axes act only on admin features. I was wondering if we could have another setting: a list of paths where Axes wouldn't log anything, like it wasn't even enabled?

**Comment by aleksihakli** [comment]
Sure it's possible. But what are the API calls and overheads you are concerned about? The idea of this project is to prevent brute forcing authentication attempts. If you only enable security features on part of the web site you might just as well disable it. What is the concrete use case you wish to support?

**Comment by vschettino** [comment]
OK! I'll explain my scenario:  I'm using [DRF rate limit features](https://www.django-rest-framework.org/api-guide/throttling/) with some custom configuration to secure my endpoints. I'd like django-axes to take care of throttle only on my admin site, without interaction with my login endpoints that are already handled by DRF. The flag "AXES_ONLY_ADMIN_SITE" led me to think that all Axes action would be limited to the admin site.

**Comment by simoroma** [comment]
I cannot make `AXES_ONLY_ADMIN_SITE = True` to work. It stills lock out users everywhere. I even tried to dig into the code. I am using Axes version 5.6.2. I am also using Allauth. Is there any conflict with this?

**Comment by aleksihakli** [comment]
Hey @simoroma! The lock does not actually disable the locking mechanism elsewhere, check the following code path: 

https://github.com/jazzband/django-axes/blob/master/axes/handlers/base.py#L136

The implementation or documentation could be improved a bit in this regard.

**Comment by simoroma** [comment]
Thanks for the super fast reply!

I am using Django 3.1 and Allauth 0.42.0

**Comment by aleksihakli** [comment]
Well, we do have users using Allauth, but it might require a bit of customization to work smoothly. Have you taken a look into the Allauth integration documentation here and have you specialized the code in any way so far? Please note that the documentation is probably based on an older version of Django as well as Allauth.

https://django-axes.readthedocs.io/en/latest/6_integration.html

I don't think I have integrated Axes with Allauth myself, but I suspect it's possible to do the integration. However, Allauth is such a complex project (and Axes has some complexity as well) that you might have to take a look at the source code and login design to see if the configuration or login flow needs to be specialized.

If you are taking a look into this it would be awesome if you can spare the insight and possibly see if the documentation is up-to-date as well? If you'd like to make and contribute any updates on it, it's easy to open a PR via the built-in GitHub editors as well. They should understand the rST format pretty well, so you can just fork the repo and open a PR after editing 👍

**Comment by simoroma** [comment]
Thanks, I will try to have a look into it then.

I haven't implemented that bit about integration with Allauth. Nonetheless, everything seems to work smoothly. Locking out users work well and all logins and attempts are stored in the DB. 

Checking the function you linked for `AXES_ONLY_ADMIN_SITE` it seems that it should just work by matching the path. Allauth is using different paths from the administration page path `/admin`. That is why I was thinking it could have worked off the box.
