### ISSUE TITLE
Django test client compatibility

### ISSUE THREAD

**Issue by MWedl** [jazzband/django-axes#433]
Since version 5, when using the `login` and `force_login` methods of the django test client (django version 1.11), exceptions get thrown and tests fail.

When using `force_login()` the django test client uses an instance of `HttpRequest`, but axes requires an `AxesHttpRequest`.
```
from django.test import Client
client = Client()
client.force_login(user)

Traceback (most recent call last):
  File "/vagrant/src/project/tests/tests_integration.py", line 87, in setUp
    client.force_login(user)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/test/client.py", line 645, in force_login
    self._login(user, backend)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/test/client.py", line 658, in _login
    login(request, user, backend)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 161, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/axes/signals.py", line 26, in handle_user_logged_in
    AxesProxyHandler.user_logged_in(*args, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/axes/handlers/proxy.py", line 52, in user_logged_in
    return cls.get_implementation().user_logged_in(sender, request, user, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/axes/handlers/database.py", line 141, in user_logged_in
    clean_expired_user_attempts(request.axes_attempt_time)
AttributeError: 'HttpRequest' object has no attribute 'axes_attempt_time'
```

When using `login()` the test client uses `request=None` to authenticate.
```
from django.test import Client
client = Client()
client.login(user=user.email, password="SecurePassword123")

Traceback (most recent call last):
  File "/vagrant/src/project/tests/tests_integration.py", line 89, in setUp
    client.login(user=user.email, password="SecurePassword123")
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/test/client.py", line 628, in login
    user = authenticate(**credentials)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.6/site-packages/axes/backends.py", line 33, in authenticate
    raise AxesBackendRequestParameterRequired('AxesBackend requires a request as an argument to authenticate')
axes.exceptions.AxesBackendRequestParameterRequired: AxesBackend requires a request as an argument to authenticate
```

**Comment by tamhv** [comment]
`AttributeError: 'HttpRequest' object has no attribute 'axes_attempt_time'`
hi bro, i'm about to report the same issue, but i can get over it by using AxesDummyHandler 
```
from django.test import override_settings
@override_settings(AXES_HANDLER='axes.handlers.dummy.AxesDummyHandler')
class MyTest(TestCase):
    def test_blabla(self):
          ...
```

**Comment by MWedl** [comment]
Thank you, but you would have to add `@override_settings` to every test class which requires authentication. That is not an optimal solution, in my opinion.

**Comment by beaugunderson** [comment]
also a dealbreaker for us, we use `django-session-security` which calls `logout(request)` in one code path which is a `WSGIRequest` which does not have `axes_attempt_time`

**Comment by tamhv** [comment]
@MWedl you may have a separate test settings file, put `AxesDummyHandler` there, then you don't have to use `@override_settings` in test class
```
#settings/test.py

...
AXES_HANDLER = 'axes.handlers.cache.AxesCacheHandler'
```

**Comment by aleksihakli** [comment]
Hi, and thanks for reporting the issue. Do you have the Axes middleware in the `MIDDLEWARE` list and does `force_login` bypass it? Can you use `AxesDummyHandler` for your test settings like @tamhv suggested?

**Comment by MWedl** [comment]
@aleksihakli yes, AxesMiddleware is in the `MIDDLEWARE` list and `force_login()` works with `AxesDummyHandler`. But `login()` still throws the Exception.

`force_login()` creates a `HttpRequest` and calls `django.contrib.auth.login`, which sends the `user_logged_in` signal. Yes, the middleware is bypassed.

**Comment by aleksihakli** [comment]
You can disable Axes in your test setup to circumvent the problem. Just drop it from
`INSTALLED_APPS` in your test settings. We will check if the problem can be easily circumvented.

One option would be to add a flag like `AXES_ENABLED` 
with a default value of `True` that could be used to disable Axes in the test setup, but that would be effectively the same as removing Axes from `INSTALLED_APPS` anyway.

A better solution would be coping with the missing request, but then Axes would not function correctly at all since it needs the request attributes for correct behaviour.

We will need to function correctly with `login` and `logout` so fixing or documenting this bug is a priority.

**Comment by aleksihakli** [comment]
@MWedl @beaugunderson @tamhv I've made a fix in #435. If you use ``AXES_ENABLED = False`` in your test settings the test logic should work. I'm rolling out a 5.0.2 release for the fix.

**Comment by aleksihakli** [comment]
One OK option might be to use something like

    import sys
    AXES_ENABLED =

**Comment by beaugunderson** [comment]
@aleksihakli thanks for the quick work on this--i should clarify that the errors i see aren't related to tests though, so we still need a solution for `login`/`logout`/etc. outside of tests :)

**Comment by aleksihakli** [comment]
I seem to have misread @beaugunderson (although the original issue was about the test client methods).

You could fix that logout error with the following handler definition in a custom `handlers.py` module:

```python
from axes.handlers.database import AxesDatabaseHandler

class MyHandler(AxesDatabaseHandler):
    def user_logged_out(self, sender, request, user, **kwargs):
        if request:  # or a similar check per your preference
            super().user_logged_out(sender, request, user, **kwargs)
```

and then use something like

```python
AXES_HANDLER = `path.to.handlers.MyHandler`
```

You can specialize the stock handlers or use your own as you would like. You can similarly tune the methods you want for the other handlers. Check the handler source code for reference.

I don't see `django-session-security` using `login` method anywhere? The only reference to `logout` I found was [here](https://github.com/yourlabs/django-session-security/blob/5845c55f1c4b8cef8362302d64b396fc705e1a10/session_security/middleware.py#L75), so fixing that logout handler should be enough to fix the correct functionality?

**Comment by aleksihakli** [comment]
@beaugunderson I implemented a fix in 88699cf6193ea473f4468c709c50e49ec1911500 and rolled it out in release 5.0.3 which is now in PyPI, could you check if that works for you?

**Comment by felipe3dfx** [comment]
We need add request parameter when using authenticate function on custom login view, other way it not works:

https://docs.djangoproject.com/en/2.2/topics/auth/default/#authenticating-users
example:
```python
user = authenticate(
    request=self.request, # must be set
    username=form.cleaned_data.get('email'),
    password=form.cleaned_data.get('password1'),
)
login(self.request, user)
```

**Comment by beaugunderson** [comment]
@aleksihakli 

> @beaugunderson I implemented a fix in 88699cf and rolled it out in release 5.0.3 which is now in PyPI, could you check if that works for you?

5.0.3 is working well, had to add the request to `authenticate()` in one place in our code but other than that, smooth sailing!

**Comment by aleksihakli** [comment]
Let's add this to the official documentation.

**Comment by aleksihakli** [comment]
The docs now have a [section](https://django-axes.readthedocs.io/en/latest/3_usage.html#authenticating-users) on customizing user authentication and passing the `request` arg to `authenticate`.

**Comment by deZKI** [comment]
I have the same issue. you can setup a special test runner like this   
from django.conf import settings
from django.test.runner import DiscoverRunner


class TestSuiteRunner(DiscoverRunner):

    def setup_test_environment(self, **kwargs):
        super().setup_test_environment(**kwargs)
        settings.AXES_ENABLED = False
and add it in you settings file TEST_RUNNER = '....TestSuiteRunner'

Or define a new setting file
also do not forget that you can override settings for special test

i suppose that it is easy to set a default runner with no axes. and if you want to test axes you will use @override_settings
