### ISSUE TITLE
`is_already_locked` gone after update

### ISSUE THREAD

**Issue by GitRon** [jazzband/django-axes#439]
Hi guys,

I was using `is_already_locked` (from axes.attempts import is_already_locked) in my custom serializer and after the update it seems to be gone without a comment in the changelog.

1) Maybe this change should be mentioned in the changelog?

2) What would be the best way to get this functionality back?

Thanks!
Ronny

**Comment by GitRon** [comment]
Ok, after going through the git history, this might be the solution:

Previous:

   from axes.attempts import is_already_locked
   if is_already_locked(request, credentials):
      ...

New:
   if AxesProxyHandler.is_locked(request, credentials):
      ...

Can somebody confirm this? :)

**Comment by aleksihakli** [comment]
Hey @GitRon! You are correct, the old `is_already_locked` API has been deprecated and moved into the handler API in the latest major release version 5. This could be better documented in the change log, it really just needs an update line. The new public handler API is now officially documented and can be considered stable for use.

**Comment by GitRon** [comment]
Alright! Thanks :)

**Comment by aleksihakli** [comment]
I've added a changelog entry for this on 5.0 since that was the version where the API deprecated.

**Comment by GitRon** [comment]
Awesome! Thanks!
