### ISSUE TITLE
django-reversion compability

### ISSUE THREAD

**Issue by GitRon** [jazzband/django-axes#440]
Hi guys,

following thing: I'm using django-rest-framework and want to secure my backend with axes. 

When I use the default database table type "InnoDB" axes cannot save or update failed attempts in the tables. When I change the table type to "MyIsam", it works.

I just updated to the latest version. Same as before. Super strange but I couldn't figure out why this happens.

Best
Ronny

**Comment by aleksihakli** [comment]
This might be somehow related to #442 and needs to be investigated further. Are you running with transactions and auto commit mode on with the InnoDB engine?

**Comment by GitRon** [comment]
I checked it. I stick to MariaDB default behavior so I guess I have `autocommit` on and for transactions... again I just use it like django does. Nothing fancy there.

Does this help somehow? Can I help somehow?

**Comment by aleksihakli** [comment]
Reporting the issue was plenty of help! I've implemented an alternative way for marking the requests for lockout in #443 which should fix the issue for DBs with atomic requests and transaction rollbacks.

**Comment by aleksihakli** [comment]
@GitRon would you mind checking if version 5.0.5 fixes the issue for you? It is released on PyPI.

**Comment by GitRon** [comment]
Unfortunately not working when I go via djano REST. The moment I change the collation of the table, it works.

**Comment by aleksihakli** [comment]
@GitRon that's weird, I guess we're missing something in the flow then.

Would you mind posting your redacted database and table settings for reference along with the commands that fix the functionality?

**Comment by aleksihakli** [comment]
@GitRon do you have your working configuration available? It would really help in debugging the problem here.

**Comment by GitRon** [comment]
@aleksihakli Busy sprint but I try to create a project where we can see this error. Hope I get this done anytime soon!

**Comment by GitRon** [comment]
@aleksihakli Super weird. Created the same base setup and works. The bug must be with some third party component which interferes one way or the other. I'll keep posting my updates.

**Comment by GitRon** [comment]
@aleksihakli I found the bad guy! I tried to debug it with no success but the problem occurs only if I put `reversion.middleware.RevisionMiddleware` from the [django-reversion](https://github.com/etianen/django-reversion) in my settings.

Maybe you have more luck finding out why this is interfering with your logic... 🤔

**Comment by aleksihakli** [comment]
Good find! I updated the title.

It seems like the villain might be [this logic](https://github.com/etianen/django-reversion/blob/master/reversion/middleware.py#L45)

It fetches the exceptions from the stack and reacts to PermissionDenied being raised in the authentication backend, which should only block the current request from being processed.

**Comment by aleksihakli** [comment]
Opened an issue ticket in https://github.com/etianen/django-reversion/issues/792

**Comment by GitRon** [comment]
Great! Thanks! Hopefully they'll be able to fit it!

**Comment by mark-mishyn** [comment]
I just put my solution, maybe it will be usefull for someone. 
It's monkey patch to skip reversion logic on login views.

`from reversion import views
from django.urls import resolve

def _request_creates_revision(request):
    if resolve(request.path_info).url_name.endswith('login'):
        return False

    return request.method not in ("OPTIONS", "GET", "HEAD")

views._request_creates_revision = _request_creates_revision`

**Comment by aleksihakli** [comment]
@mark-mishyn that seems like a decent workaround. Would you mind opening a PR for the docs integration page?

https://github.com/jazzband/django-axes/blob/master/docs/6_integration.rst

**Comment by aleksihakli** [comment]
@mark-mishyn I added the note and it is now available on RTD for everyone:

https://django-axes.readthedocs.io/en/latest/6_integration.html

**Comment by mark-mishyn** [comment]
Thank you @aleksihakli !

There is simple patch to the doc to fix the case when view doen's have name.
https://github.com/jazzband/django-axes/compare/master...mark-mishyn:patch-1
