### ISSUE TITLE
Reset does not work correctly with the cache backend

### ISSUE THREAD

**Issue by felipe3dfx** [jazzband/django-axes#454]
Axes commands axes_reset and axes_reset_username not working, always give 'No attempts found.' 

```bash
$ python3.6 manage.py axes_reset_username 'example@example.com'
No attempts found.
```

```bash
$ python3.6 manage.py axes_reset
No attempts found.
```

i have the following configuration:

settings.py
```python
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
]

AXES_FAILURE_LIMIT = 10
AXES_ONLY_USER_FAILURES = True
AXES_COOLOFF_TIME = 24
AXES_LOCKOUT_TEMPLATE = '429.html'
AXES_CACHE = 'axes'
AXES_HANDLER = 'axes.handlers.cache.AxesCacheHandler'

REDIS_HOST = 'redis'
REDIS_PORT = 6379
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'sessions': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'compress': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/3',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'axes': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/4',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
}
```

requirements.txt
```text
django==2.2.2

channels==2.2.0
coverage==4.5.3
gunicorn==19.9.0
holidays==0.9.10
huey==2.1.0
ipython==7.5.0
pillow==6.0.0
piprot==0.9.10
prospector==1.1.6.4
psycopg2-binary==2.8.3
pytest-cov==2.7.1
pytest==4.6.3
python_dateutil==2.8.0
python_magic==0.4.15
raven==6.10.0
requests==2.22.0
tblib==1.4.0
uvicorn==0.7.2

dj-inmemorystorage==1.4.1
django-admin-sortable==2.1.15
django-axes==5.0.7
django-compressor==2.3
django-constance==2.4.0
django-debug-toolbar==1.11
django-dynamic-fixture==2.0.0
django-extensions==2.1.9
django-hashid-field==2.1.6
django-ipware==2.1.0
django-qr-code==1.0.0
django-redis==4.10.0
django-widget-tweaks==1.4.5
pytest-django==3.5.0
```

**Comment by aleksihakli** [comment]
Hey @felipe3dfx! Due to how`axes.handlers.cache.AxesCacheBackend` is implemented, the username reset does not function with the cache backend. 

The reason is that the cache backend uses a hash in the cache that is calculated from multiple different elements. The implementation can be found [here](https://github.com/jazzband/django-axes/blob/9fa0e7f2158921380922b8d1081e6fdb8f5d171b/axes/helpers.py#L362).

If you can figure out a good way for implementing the resets in the cache handler that would be most welcome contribution.

**Comment by aleksihakli** [comment]
The handlers that can not reset attempts now raise a `NotImplementedError` on invalid command execution. The database handler handles resets for the access attempts and logs correctly.

**Comment by aleksihakli** [comment]
The approach does look valid, would you be interested in opening a PR for getting them upstreamed with the handlers?

**Comment by fbove** [comment]
Giving it a closer look, what I'm saying it's already implemented here:

https://github.com/jazzband/django-axes/blob/7b8123a72c76893dcf42de96329ce53a2420b49d/axes/helpers.py#L177-L190

When it's called by `get_client_parameters` in:

https://github.com/jazzband/django-axes/blob/7b8123a72c76893dcf42de96329ce53a2420b49d/axes/helpers.py#L226

So it won't consider `ip_address` and `user_agent`.

**Comment by nattyg93** [comment]
Hi @aleksihakli I would be happy to consider looking at writing a PR for this if it is something that is still desired. Could I possibly get a bit of guidance?

**Comment by aleksihakli** [comment]
Hi @nattyg93! If you want to get started with PRs you can refer to the Axes documentation which describes the development process: https://django-axes.readthedocs.io/en/latest/9_development.html

The discussion and work outlined here pretty much describes the desired outcome and things that need to be implemented for it to work. If you have any specific questions please ask away!
