### ISSUE TITLE
Add reset command for Access logs

### ISSUE THREAD

**Issue by OndrejIT** [jazzband/django-axes#455]
Because deleting in admin interface is slow and command can be run by cron..

**Comment by aleksihakli** [comment]
Hey @OndrejIT! That is a good idea, let's add this to feature requests. The feature should be relatively simple in itself. 

I'd imagine that adding a parameter for setting the age would be good since most people probably would like to remove access logs that are e.g. over a month old.

**Comment by aleksihakli** [comment]
Resolved by PR #460 @OndrejIT :)
