### ISSUE TITLE
Lockout registered users only on Django admin

### ISSUE THREAD

**Issue by yuri644nds** [jazzband/django-axes#458]
Is there a way to lockout registered users only on Django admin.

**Comment by aleksihakli** [comment]
Hey @yuri644nds! Currently there isn't, and there is a ticket open on the issue at #432. Please check that issue and the discussion. I'm closing this as a duplicate issue.

**Comment by aleksihakli** [comment]
Lockout for admin only has been implemented by @hramezani and released in 5.0.8 @yuri644nds.
