### ISSUE TITLE
'WSGIRequest' object has no attribute 'axes_ip_address'

### ISSUE THREAD

**Issue by beaugunderson** [jazzband/django-axes#464]
A minority of requests to our application fail with the error `'WSGIRequest' object has no attribute 'axes_ip_address'`.

I can't figure out why the request object is not updated via the axes middleware for these requests.

JWT authentication is potentially implicated; we use a middleware to enable JWT authentication passed in via basic auth headers. We call `auth.authenticate` from this middleware, which eventually leads down into axes code via `backend.authenticate`.

I think it makes sense to add the Axes middleware BEFORE our basic auth middleware, instead of as the last middleware as documented in the installation documentation. Does that make sense?

**Comment by beaugunderson** [comment]
It appears that the update doesn't happen in the middleware in the most recent version of django-axes, so I'll also try upgrading to that.

**Comment by beaugunderson** [comment]
(To be concrete, we were on 5.0.3, will try with 5.0.9)

**Comment by aleksihakli** [comment]
Hey @beaugunderson! We changed the way the attribute resolution is done because many tools supply other requests than the normal `HttpRequest` to middleware, views, and other functions.

It is probable that the `WSGIRequest` object is supplied from a 3rd party Django plugin and

**Comment by beaugunderson** [comment]
I think you are right that 5.0.9 will likely fix the issue--I'm currently testing that hypothesis now. :)

**Comment by beaugunderson** [comment]
I haven't seen this error in production since deploying 5.0.9 everywhere but there also weren't many people using the application at that point in the day--if I don't report back by tomorrow end of day feel free to close this issue. :)

**Comment by aleksihakli** [comment]
Sounds good. I'll leave this issue open for a while so we can track if anyone else faces these issues.

Request parsing is generally volatile with different request object types and is not trivial with Django apps so I wouldn't be surprised if improvements can be implemented :)

**Comment by aleksihakli** [comment]
I'm closing this for now as it's Friday and everything appears to be well in version 5.0.9 :)
