### ISSUE TITLE
Axes Django Backend Admin

### ISSUE THREAD

**Issue by Neuroforge** [jazzband/django-axes#465]
Hello,

i am trying to control lockouts via the admin page in Django.

Axes appears to work, but there is no way to reset access via the admin page.  This has been addressed before, but documentation has been provided.

https://github.com/jazzband/django-axes/issues/9

Any advice would be appreciated.

Regards,

Daniel

**Comment by aleksihakli** [comment]
Did you figure this out already? Should we perhaps improve the docs?
