### ISSUE TITLE
Thank you to all project contributors

### ISSUE THREAD

**Issue by camilonova** [jazzband/django-axes#466]
@aleksihakli YOU ARE FUCKING AWESOME!!!

Thanks for all the work you have given us to make this project better.

![Bravo](https://media.giphy.com/media/kdQuvu0LtCEjxYgTcS/source.gif)

**Comment by aleksihakli** [comment]
Thank you for contributing and giving your time to a lot of projects as well, including this one :) It is nice to work on Axes with all the awesome people who have contributed into the joint effort :+1:
