### ISSUE TITLE
All users locked out

### ISSUE THREAD

**Issue by willslater** [jazzband/django-axes#474]
I have just upgraded to Python 3.6 and Django 2.2.2. 

I seem to have issue on live environment where if 1 user gets locked out then all users face the same lock out. 

Whilst i debug, is there any way to easily temp disable Axes so that I can avoid this issue, without having to comment out all references to AXEs. I couldn't find any options in docs to set AXES = False or something.

**Comment by markddavidoff** [comment]
Simply comment it in the auth middleware, should prevent it being loaded during the auth flow.

**Comment by aleksihakli** [comment]
You can also use the `AXES_ENABLED` configuration flag for disabling the plugin functionality. Please refer to the [configuration documentation](https://django-axes.readthedocs.io/en/latest/4_configuration.html) for more information.

**Comment by sabanak** [comment]
Is there any option for locking user by there email and IP instead of username and IP by using django-axes ?
