### ISSUE TITLE
Add ability to specify AXES_COOLOFF_TIME as callable object

### ISSUE THREAD

**Issue by DariaPlotnikova** [jazzband/django-axes#475]
It's useful that ``AXES_FAILURE_LIMIT`` can be not only hardcoded value but also callable object, that returns value at runtime. But it's not possible for setting ``AXES_COOLOFF_TIME``. 
I'd like to contribute to source code to add this functionality asap.

**Comment by aleksihakli** [comment]
Sounds like a good idea, thanks for your interest! Jazzband is always open for PRs. 

The current implementation for getting the cooloff is [here](https://github.com/jazzband/django-axes/blob/2fcf439683d09b297575e316b01620a20721ed56/axes/helpers.py#L44) and it is called from [here](https://github.com/jazzband/django-axes/blob/2fcf439683d09b297575e316b01620a20721ed56/axes/helpers.py#L272) and [here](https://github.com/jazzband/django-axes/blob/26cc41b68927e4044674f4e2ef87057c30663df4/axes/attempts.py#L18).

Please bear in mind that the cooloff needs to be usable from the queryset filtering and it needs to be well tested, so if you add new features, they need to have tests for getting upstreamed. The cooloff calculation is a central feature and needs to work correctly in order for security features to function.

**Comment by aleksihakli** [comment]
Released in version 5.0.12.
