### ISSUE TITLE
AxesBackend requires a request as an argument to authenticate

### ISSUE THREAD

**Issue by tantheeta** [jazzband/django-axes#478]
Hi ,
 we have been using 'rest_framework.authtoken' for JW token creation for users.
We have recently added django axes for implementing captcha functionality.
However, it;s throwing below error:
 
AxesBackendRequestParameterRequired at /api/api-token-auth/
AxesBackend requires a request as an argument to authenticate

as an FYI, the authentication backend looks like this:
AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

Could you please advise on this.

**Comment by aleksihakli** [comment]
Hey! Axes is not really meant for captcha, it is intended for authentication (login) attempt tracking. Are you sure about your use case?

Could you post your Django, DRF, and Axes versions and DRF configuration for reference?
