### ISSUE TITLE
Add Django REST Framework JSON payload support for login

### ISSUE THREAD

**Issue by msaysell** [jazzband/django-axes#495]
Consider the following curl request:

```
curl --request POST \
  --url http://localhost:8000/login/ \
  --header 'content-type: application/json' \
  --data '{
    "username" : "auser@foo.com",
    "password" : "dshtyh"
}'
```

Django rest framework places the data payload for the above in its `request.data` as opposed to the `request.POST` dictionary

https://www.django-rest-framework.org/tutorial/2-requests-and-responses/#request-objects

As such, any username is not picked up which practically breaks any integration that doesn't use IP or user agent to cross protect because of the following line of code

https://github.com/jazzband/django-axes/blob/master/axes/helpers.py#L145

**Comment by aleksihakli** [comment]
Hey,

and good catch. You can use the `AXES_USERNAME_CALLABLE` setting to circumvent this problem in your `settings.py`:

    AXES_USERNAME_CALLABLE = lambda request, credentials: request.data["username"]

Remember to check that you have the [JSON parser in your DRF parsers](https://www.django-rest-framework.org/api-guide/parsers/).

If you'd like, improving this via PR would be great. If the `request` has the `data` attribute it could be better to use that than the request.POST attribute, so this could be a fairly simple improvement to implement.

Just bear in mind, that there are many users with many different configurations running that supply many different kinds of request objects to the backend, so the solution should ideally be non-invasive.

**Comment by msaysell** [comment]
Hey alek

**Comment by aleksihakli** [comment]
Yeah

**Comment by msaysell** [comment]
Sorry I clicked the wrong button and didn't mean to close the issue...

The fix I used locally is:

```
def _get_username(request, credentials):
    data_username = None
    if hasattr(request, 'data'):
        data_username = request.data.get("username")
    return data_username or request.POST.get("username")


AXES_USERNAME_CALLABLE = _get_username
```
(we use a linting tool that doesn't allow lambdas)

**Comment by aleksihakli** [comment]
@msaysell would you be interested in opening a PR for enabling DRF support for others with this?
