### ISSUE TITLE
Single '}' encountered in format string

### ISSUE THREAD

**Issue by zerolab** [jazzband/django-axes#501]
We had someone trying to be "smart" and trying to login with a specially crafted username. e.g. `butterfly.. },,,`

This resulted in a `ValueError` exception (`Single '}' encountered in format string`)
in axes/helpers.py in get_client_str at line 230 after being dispatched from `handle_user_login_failed`

**Comment by aleksihakli** [comment]
Hey! Thanks for reporting. This needs to be checked ASAP as getting format strings in this flow is a possible security flaw. This seems related to logging in [`get_client_str`](https://github.com/jazzband/django-axes/blob/master/axes/helpers.py#L241).

**Comment by aleksihakli** [comment]
Fix rolled out in release 5.0.16 and available now on PyPI.

Leaving PR open for review and discussion purposes as this is a possible security flaw.

**Comment by aleksihakli** [comment]
@camilonova would you mind taking a look at issue and related PR for resolution?

**Comment by aleksihakli** [comment]
Master now has even better string formatting with the safer [`string.Template`](https://docs.python.org/3/library/string.html#template-strings).

**Comment by aleksihakli** [comment]
This shouldn't be an issue anymore so closing this ticket. I searched the codebase and we don't have any volatile uses of format in the codebase anymore; this was caused by a duplicate invocation of both f-string and `str.format` call.

**Comment by zerolab** [comment]
Thank you for the speedy fix, @aleksihakli 
Works like a charm!
