### ISSUE TITLE
How to disable logging when running tests?

### ISSUE THREAD

**Issue by lifecrisis** [jazzband/django-axes#507]
Greetings,

I'd like to implement some tests that verify that axes is installed and configured properly in my project.  When i run my tests I get logging messages on stderr that appear like the following:

```
AXES: New login failure by {username: "foo", ip_address: "127.0.0.1", user_agent: "<unknown>", path_info: "/login/"}. Creating new record in the database.
```
I'd like a test that simulates a basic brute force attack and then verifies that the IP or user or User-Agent is locked out.  These are very noisy when I have such a test.

How can I silence these?

Thanks!

**Comment by aleksihakli** [comment]
Configure logging for the ``AXES_LOGGER`` to not log into console or other target that is too noisy.

There are plenty of examples and documentation around for setting up Django ``LOGGING`` with different configurations.

**Comment by PierrePaul** [comment]
I know this is closed and quite old, but just in case someone else find this, here is a more complete answer :
```python
AXES_LOGGER = "axes.watch_login"
logger = getLogger(AXES_LOGGER)
logger.setLevel(CRITICAL)
```
That would go into your settings configuration.

**Comment by aleksihakli** [comment]
Looks like a good solution. You can also define that in your project Django configuration. It's usually good to have a separate configuration for tests with a simpler password hashing algorithm etc.
