### ISSUE TITLE
django-graphql-jwt integration

### ISSUE THREAD

**Issue by ckristhoff** [jazzband/django-axes#511]
Hi everyone

I'm searchin how to integrate Axes with django_graphql_jwt.
Errors inside mutations raises exceptions and the library catch it and response to user with right graphql format, but axes lockout response redirect and blocks the JWT process.

Some ideas?

**Comment by aleksihakli** [comment]
You can add a new feature to the `get_lockout_response` that can be used for GraphQL and open a PR for it:

https://github.com/jazzband/django-axes/blob/cd75ef45105b12c756dac29e1b171766a5fe9293/axes/helpers.py#L280

A custom function for returning a lockout response could be implemented similar to how cool off and failure limit are currently done. 

You could add a configuration key such as `AXES_LOCKOUT_RESPONSE` that could be configured to a str pointing to a callable or a callable itself that takes request and credentials parameters. 

For example:

```
AXES_LOCKOUT_RESPONSE = 'package.module.get_graphql_response`

# or

AXES_LOCKOUT_RESPONSE = lambda request, credentials: return None
```

Then you can add a handler for the configuration value into the existing function and be happy.

You can inspect the current codebase in `axes/conf.py` and `axes/helpers.py` to refer how the flags are implemented now.

If you add the configurations, please add unit tests for them as well. The unit tests can have a simple and minimal implementations similar to the current tests.

**Comment by aleksihakli** [comment]
Hey @ckristhoff. The lockouts are now configurable with a flag, check the associated PR for more information.

**Comment by stephenmullens** [comment]
> Hi everyone
> 
> I'm searchin how to integrate Axes with django_graphql_jwt. Errors inside mutations raises exceptions and the library catch it and response to user with right graphql format, but axes lockout response redirect and blocks the JWT process.
> 
> Some ideas?

@ckristhoff Do you have an example of your django-axis and django-graphql-jwt integration which you could share?
