### ISSUE TITLE
User account whitelisting

### ISSUE THREAD

**Issue by denis-sumin** [jazzband/django-axes#536]
README states that django-axes features user account whitelisting, but I failed to find anything related to it in the documentation. Is it possible to whitelist a single user account?

Thanks!

**Comment by aleksihakli** [comment]
Hi Dennis. At the moment you'd have to implement the whitelisting in the codebase to achieve this functionality with either a customer handler or a customer user model. I believe the codebase is the best place to start on this.

It would be a nice option to have e.g. a function configurable in settings that could check for whitelisting conditions. That would cover most use cases, I believe. If you're interested in implementing that functionality, please feel free to open a PR for it! 

I believe the function could take e.g. `request` and `user` object as parameters for whitelisting, like so:

```
def is_whitelisted(request, user):
    if user.username == 'whitelisted':
        return True
```
