### ISSUE TITLE
ModuleNotFoundError: No module named axesusers

### ISSUE THREAD

**Issue by skuflow** [jazzband/django-axes#544]
I've made the adjustments to my django settings file and am getting this message.  I do not see any reference anywhere to this module.  Any ideas?

**Comment by aleksihakli** [comment]
Hi @skuflow! What are the adjustments you have made? What is the full error message? Have you tried searching for the error text in your project?

**Comment by skuflow** [comment]
That’s the error.  I followed the setup steps here: 

https://django-axes.readthedocs.io/en/latest/2_installation.html

axesuser is not in our code base.

**Comment by aleksihakli** [comment]
Have you checked your `INSTALLED_APPS` list for missing commas or typos?

**Comment by skuflow** [comment]
Missing comma.   Thanks!

**Comment by aleksihakli** [comment]
Nice, closing the issue!
