### ISSUE TITLE
login with correct credentials is locking too

### ISSUE THREAD

**Issue by antuaneacion** [jazzband/django-axes#564]
djago-axe is locking login with correct credentials 

django-axe is locking every attempts of login even with the right credentilas, my site is developed with the Django admin site.
this is my url for login
path('login/', LoginView.as_view(template_name='app/login.html', redirect_authenticated_user=True), name='login'),

**Comment by aleksihakli** [comment]
Hey @antuaneacion! Did you figure out the problem?

**Comment by antuaneacion** [comment]
yes I did. I needed to put this in the AUTHENTICATION_BACKENDS 
# Django ModelBackend is the default authentication backend.
  'django.contrib.auth.backends.ModelBackend',
thanks anyway
