### ISSUE TITLE
Integration with DRF

### ISSUE THREAD

**Issue by I0x4dI** [jazzband/django-axes#571]
Hello.
My project uses Django Admin and Django Rest Framework.
I set the flag AXES_REST_FRAMEWORK_ACTIVE to true.
And I got the library exception, when I logged in Django admin.

> AttributeError at /admin/login/
> Exception Type: 	AttributeError
> Exception Value: 	'WSGIRequest' object has no attribute 'data'
> Exception Location: 	/lib/python3.6/site-packages/axes/helpers.py in get_client_username, line 147

Thank you for your work!

**Comment by aleksihakli** [comment]
Thanks, good catch! Upstreaming the proposed change.

**Comment by aleksihakli** [comment]
@I0x4dI your PR is now released in 5.3.0 on PyPI :)
