### ISSUE TITLE
Some tables does not exist

### ISSUE THREAD

**Issue by AliYmn** [jazzband/django-axes#591]
Hi, When i login, I get some error about "does not exist".

```
django.db.utils.ProgrammingError: column axes_accessattempt.trusted does not exist
LINE 1: ...t"."ip_address", "axes_accessattempt"."username", "axes_acce...
```

**Comment by aleksihakli** [comment]
Have you run the migrations as per instructions in here?

https://django-axes.readthedocs.io/en/latest/2_installation.html
