### ISSUE TITLE
Dependency on Six

### ISSUE THREAD

**Issue by ChristianBell1995** [jazzband/django-axes#593]
Using Django 3.0.6, I am getting this error for the latest version of django-axes (5.3.2)

```
File "/usr/local/lib/python3.7/site-packages/axes/models.py", line 2, in <module>
     from django.utils import six
ImportError: cannot import name 'six' from 'django.utils'
```

Would it be possible to remove this dependency from the package so its compatible with Django 3.0.0+

**Comment by aleksihakli** [comment]
Hi @ChristianBell1995! Axes 5.3.2 should not have a dependency on `django.utils.six`, are you certain that you are running the correct version?
