### ISSUE TITLE
AccessAttempt is never created (axes fails to prevent django rolling back transaction when authentication has failed)

### ISSUE THREAD

**Issue by LukenAgile42** [jazzband/django-axes#611]
When I fail to login, axes creates an AccessAttempt instance, as expected. During axes runtime, AccessAttempt remains there and is not deleted. However when I fail to login a 2nd time, and axes code is again called, the AccessAttempt is already gone, even though I can find no point where it could have been deleted.

As a result, axes does not work.

**Comment by aleksihakli** [comment]
Would you mind posting your Axes configuration and any custom login code you are using?

**Comment by LukenAgile42** [comment]
We are using djoser for authentication, django 2.0

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = 1

Looking at posgres log, access_attempt is not deleted, but rather the transaction gets rolled back every time. I would assume this is actually an inbuilt safety feature of django to not allow unauthenticated user to make changes to the database.

**Comment by LukenAgile42** [comment]
Is there any further information that you need? Unfortunately we will have to look for another solution if we cant get an answer here.

What I dont understand is how axes even works at all, as django will rollback the transaction when authentication fails and no AccessAttempt instance will be created. Yet apparently it magically works for everyone else (I cant even any issues that mentions this problem at all).

**Comment by aleksihakli** [comment]
What is actually causing the transaction rollback? You probably have a plugin or another component that is performing the rollback in the stack. Transaction rollbacks are a known issue with the database handler if you are using e.g. django-reversion:

https://github.com/jazzband/django-axes/issues/440

Would you mind posting your full plugin and Django configuration so that we have more information on the issue?

One option would be to use another handler such as the cache handler with Redis or Memcached for storing the access attempts.

Just as a note, you do realize that this project is unfortunately free of charge and the maintainers of FOSS projects usually do it on a voluntary basis and try and help you with your problems free of charge on their free time?

**Comment by LukenAgile42** [comment]
We do indeed use `django-reversion`, though when I removed it from installed apps and middleware and it made no difference.

```
INSTALLED_APPS = (
    'tenant_schemas', 

    'django.contrib.auth',
    'django.contrib.admin',
    'polymorphic',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_recursive',
    'axes',
    'djoser',
    'corsheaders',
    'django_nose',
    'reversion',
    'simple_history',
    'channels',
    'django_countries',

    'etf.core',
    'etf.api',
    'etf.clients',
    'etf.demographics',
    'etf.public'
)

MIDDLEWARE = (
    'tenant_schemas.middleware.TenantMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reversion.middleware.RevisionMiddleware',
    'axes.middleware.AxesMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
)
```

How do I reconfigure axes to use `redis`?

**Comment by LukenAgile42** [comment]
But actually I dont think `django-reversion` is the problem.

`djoser` tries to authenticate the user. 

`self.user = authenticate(
            username=attrs.get(User.USERNAME_FIELD),
            request=self.context.get('request'),
            password=attrs.get('password')
        )`

And when it fails, `rest_framework` is called which raises a validation error.
`raise ValidationError(message_string, code=key)`

django then rolls back when the exception has been raised which is the expected behaviour for django.

From [djangos doucmentation](https://docs.djangoproject.com/en/2.0/topics/db/transactions/)

> Before calling a view function, Django starts a transaction. If the response is produced without problems, Django commits the transaction. If the view produces an exception, Django rolls back the transaction.

**Comment by aleksihakli** [comment]
[If you are using the Axes database handler and have enabled ATOMIC_REQUESTS in Django then Django will indeed roll back the transactions](https://docs.djangoproject.com/en/3.0/topics/db/transactions/#tying-transactions-to-http-requests) and there's nothing we can do about in the Axes database handler or outside Django, as the transaction is started when the request starts and either committed or rolled back at the end of the transaction. If you examine the Axes and Django source code you will find out which exceptions are OK and which cause a rollback. For example, an authentication failure will not cause rollbacks.

If you are using a plugin that throws exceptions that roll back the transactions then you can either [configure a different handler](https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-handlers) or even implement a custom handler for your project. You can just utilize Memcached or Redis for tracking the logins; that should handle most cases of e.g. bruteforcing that is commonplace. The database handler is the default as it offers the correct functionality for most people, but obviously it has pitfalls and doesn't suit every case and project configuration.

If you'd like to improve the handler rollback behaviour then there is room for that in Django. Ideally, causes of rollbacks should be configurable by cause, but the current design doesn't make that very feasible. Implementing a clean solution for configurable transactions, waiting it to be possibly upstreamed and then waiting for a release would possibly take years and be backwards incompatible though, as the feature would be added in the next release at the earliest, and features aren't commonly backported for earlier framework versions.

There's some [discussion on the Axes architecture](https://django-axes.readthedocs.io/en/latest/7_architecture.html) if you want to get more in-depth with the design. Do note that Axes is a 10-year-old project and many of the solutions and project structure stem from earlier design decisions and constraints that come from Django itself and other plugins that are commonly used with this project. Contributions are always welcome and if you'd like to improve the Django security landscape, many projects as well as the framework core project have opportunities for that :)
