### ISSUE TITLE
Add support for Django 3.0.3

### ISSUE THREAD

**Issue by edenorca** [jazzband/django-axes#614]
Hi,

I tried using this package for Django _3.0.3_ (python 3.8) and it didn't work.
Also in the [documentation](**url**), it is not very clear which Django versions are supported and, looking in the source code I saw the latest Django version supported is _3.0_

Are there any expectations when will this be compatible with Django 3.0.3?

**Comment by aleksihakli** [comment]
Axes has packaging and PyPI identifiers indicating support and Django 3.0 is supported.

What is your exact problem? "Did not work" isn't an explanation that offers much to go on.

**Comment by edenorca** [comment]
Sorry, I misconfigured something. It works, thanks
