### ISSUE TITLE
Changing user.id to uuid does not trigger new migration

### ISSUE THREAD

**Issue by PierrePaul** [jazzband/django-axes#615]
I'm looking into some tips here, I'm not sure it's related to django-axes.
We recently switched the user model to use a uuid field.
We already had emaildevices setup, so the user_id field is set to `int`.
Calling `python manage.py migrate` sees no changes.

I tried to create a data migration manually to update `emaildevice`, with no success so far :

```python
class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        app_label = 'otp_email'
        super().__init__(name, app_label)

    dependencies = [
        ('myapp', '0007_auto_xxxx'),
        ('otp_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildevice',
            name='user_id',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False,
                                   primary_key=True, serialize=False,
                                   null=False, on_delete=models.CASCADE),
    ),
    ]
```
Migration doesnt crash, but doesnt update the field either.
Any tips?

**Comment by aleksihakli** [comment]
Need more information, could you post the full model and related key specs for reference? Preferably before and after the change, indicating what you expect the migration to change and what is the expected outcome.

**Comment by PierrePaul** [comment]
I'm just going to close this, sorry. Im guessing I shouldnt be messing with user_id once the project has started. Thanks for your time.
