### ISSUE TITLE
Attempts not being saved when using DRF Simple JWT

### ISSUE THREAD

**Issue by timmyomahony** [jazzband/django-axes#628]
I have Axes set up with Django Rest Framework and DRF SimpleJWT. 

- Django==3.0.5
- djangorestframework==3.11.0
- djangorestframework-simplejwt==4.1.4
- django-axes==5.4.3

I've configured everything correctly (it seems). When I try log in via the Django Admin, Axes correctly saves incorrect attempts to the DB. But when I try log in via REST API & Simple Auth, incorrect attempts are identified but are not saved to the data. 

What's really strange though is that the `runserver` logging indicates the attempt was saved to the DB:

> WARNING 2020-08-15 12:20:46,516 database 81207 123145351049216 AXES: New login failure by {username: "joebloggs@example.com", ip_address: "127.0.0.1", user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0", path_info: "/auth/api-token-auth/"}. Creating new record in the database.

So while [the attempt object is definitely getting called correctly](https://github.com/jazzband/django-axes/blob/45109341be4db1819ed67e7fac01f2916d5b1762/axes/handlers/database.py#L143), it's just not saving to the DB.

I have no idea how this is happening though. It seems to be something to do with the signal handler maybe?

**Comment by timmyomahony** [comment]
After a lot of troubleshooting, it looks like this is actually to do with having `ATOMIC_REQUESTS=True` in my settings (I didn't realise this was the case).

When logging in with SimpleJWT a `ValidationError` would be thrown if the user password was incorrect (or they were locked out). This caused the transaction to rollback, meaning the login attempt with Django Axes isn't saved (even though it looked like it was in the logs).

**Comment by aleksihakli** [comment]
Thanks! I just merged the PR and the docs should be updated on RTD in a minute 👍
