### ISSUE TITLE
IP address for access logs does not show

### ISSUE THREAD

**Issue by madebyjeroen** [jazzband/django-axes#632]
I have django-axes running with my Django app and so far everything works fine. However, in the django-axes admin section, the IP addresses do not seem to work. It just shows a "-".

Is there perhaps a setting I should configure for django-axes to enable this or is it one of my Django project settings that prevent this? Maybe one of these:

```
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 2592000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
```

**Comment by aleksihakli** [comment]
What is your proxy and how have you configured your IP address headers in Axes?

https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-reverse-proxies

**Comment by madebyjeroen** [comment]
Apparently I just had to add and configure one of the django-axes settings:

`AXES_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'X_FORWARDED_FOR', 'REMOTE_ADDR']`
