### ISSUE TITLE
Info Account locked but I can login

### ISSUE THREAD

**Issue by mario1519** [jazzband/django-axes#638]
Hello,
I am new in Dajngo,
Axes give info "Account locked: too many login attempts. Please try again later" ,
but login with good password work, how to lock account and don't let login after to many errors

My settings 

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'default_cache',
    },
    'axes_cache': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'axes_cache',
    }
}

AXES_CACHE = 'axes_cache'
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_LOGIN_FAILURE_LIMIT = 3
AXES_USERNAME_FORM_FIELD = 'username'
AXES_LOCK_OUT_AT_FAILURE = True
AXES_NEVER_LOCKOUT_GET = True

import datetime as dt
delta = dt.timedelta(minutes=3)
AXES_COOLOFF_TIME = delta
```

Marius

ps
Sorry for my english

**Comment by aleksihakli** [comment]
Hey Marius! No need for perfect English, the only language we need here is Parseltongue. I see that you are using the database for storing attempts as well as caching. What is your current database engine and Django `DATABASES` configuration?

**Comment by mario1519** [comment]
> Hey Marius! No need for perfect English, the only language we need here is Parseltongue. I see that you are using the database for storing attempts as well as caching. What is your current database engine and Django `DATABASES` configuration?

I try everything with caching and storing ;-)
 
Postgres

DATABASES = {
    
'default': {

        'ENGINE': 'django.db.backends.postgresql_psycopg2',

        'NAME': '',

        'USER': '',

        'PASSWORD': '',

        'HOST': 'localhost',

        'PORT': '5432',

    },

**Comment by aleksihakli** [comment]
Could you see what happens if you disable the Axes cache by unsetting the `AXES_CACHE` configuration key? Caching the logins does not make a huge difference unless you have a really high traffic site. I'm suspecting that the Django transaction logic and the database cache might be at play here.

**Comment by mario1519** [comment]
when i take clear configuration no settings it's working the same 
got info , but with good pasword i can login 
I have set my AUTH_USER_MODEL mamy this is problem ?

**Comment by aleksihakli** [comment]
`AUTH_USER_MODEL` could be a source for the problem. What is your user model and did you install Axes before or after customizing the user model configuration?

**Comment by mario1519** [comment]
class uzytkownicy(AbstractUser):
    """ Użytkownicy """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    p1 = models.CharField(max_length=1, default='P', verbose_name="p1")
    p2 = models.CharField(max_length=10, blank=False,verbose_name="p2")
    p3 = models.CharField(max_length=10, blank=False,verbose_name="p3")
    p4 = models.CharField(max_length=3, blank=False, verbose_name="p4 ")

axes was installed after

**Comment by aleksihakli** [comment]
I am closing this issue as we have not heard back on it for a while. Please open a new one if this is still relevant. We need more diagnostic information to be able to reproduce the possible issue.
