### ISSUE TITLE
Error fetching command 'axes_reset_user'

### ISSUE THREAD

**Issue by gthreepwood** [jazzband/django-axes#647]
Hello,

after updating to the latest django-axes (5.6.1) i've got some errors applying its migrations, since the software i'm developing is still in test i had the opportunity to start over and deleting database tables and migrations.
Unfortunately i still got this error every time i try to access django's management commands:

Error fetching command 'axes_reset_user': name 'axes_reset_username' is not defined
Command 'axes_reset_user' skipped

I am using Django 3.1.1 with postgres, before this update everything was working as it should.
Can i help in some way to understand what's happening?

Thanks
Marco

**Comment by gthreepwood** [comment]
This is the content of axes_reset_user.py

axes_reset_username.py  # type: ignore # pylint: disable=all

**Comment by aleksihakli** [comment]
Probably caused by https://github.com/jazzband/django-axes/commit/baed1377f21c13999b9ef0d217a14848a217fa2c

Will need to roll back the changes in the management command file and release 5.6.2 to fix this.

Thanks for reporting! Let’s see if we can add a regression test for this.

**Comment by aleksihakli** [comment]
Should be fixed in patch 5.6.2 release.

**Comment by gthreepwood** [comment]
Thank you very much!
I'm not skilled enough to make a patch, but the next time i wil try.

Have a nice day!
