### ISSUE TITLE
Can't localize name "AXES" on admin page

### ISSUE THREAD

**Issue by ast-kshinkawa** [jazzband/django-axes#655]
Hi team,

I will like someone to add the following attribute to app.py so we can change AXE's app name appearing on admin page for non-tech people. 

```
from django.utils.translation import ugettext_lazy as _

class AppConfig(apps.AppConfig):
...
    verbose_name = _('axes')
```

By doing this, I can change APP name appearing on django Admin page by overwriting django.po. 

Thanks in advance!

**Comment by aleksihakli** [comment]
Hi @ast-kshinkawa! Django applications API offers name and other overrides as a feature:

https://docs.djangoproject.com/en/dev/ref/applications/#for-application-users

**Comment by ast-kshinkawa** [comment]
Thanks @aleksihakli! I will try that.
