### ISSUE TITLE
No IP address for "private" IPs

### ISSUE THREAD

**Issue by pembo13** [jazzband/django-axes#657]
It would be helpful if the documentation mentioned that there's no client IP when the client IP isn't public/routeable due to how `django-ipware` behaves. I was expecting to see the correct IP address in the logs emitted by `django-axes`.

**Comment by aleksihakli** [comment]
@pembo13 would you like to add a PR describing the actual vs. expected behaviour as you would prefer it?

**Comment by pembo13** [comment]
@aleksihakli under what section would this make sense to add it?

Expected behaviour is that internal addresses such as "192.168.1.1" would show up in the logs as part of the client str, as opposed to `None`

**Comment by aleksihakli** [comment]
Whicj
