### ISSUE TITLE
Manage a different limit for IP and user failed attemps

### ISSUE THREAD

**Issue by ludsoft** [jazzband/django-axes#661]
Following #608 I have a use case for settings different limits for IP and user failed attempts. 
I would like to limit to a small number (like 5) the number of attempts that can be done before locking out the account. 
But I would like to allow up to 100 attempts per IP as most of the users on the system i want to protect are sharing the same IP. 

Would you be open to a split of `AXES_FAILURE_LIMIT` into AXES_FAILURE_LIMIT_USER and AXES_FAILURE_LIMIT_USER for the setting AXES_LOCK_OUT_BY_USER_OR_IP == True or something similar? 

Thanks a lot for your help and the project.

**Comment by aleksihakli** [comment]
Hey! You can implement this functionality by writing a custom handler and adding the options there as you would like. Check the project documentation on RTD and the proxy and database handler code on GitHub for reference.

**Comment by ludsoft** [comment]
Thanks, I'll have a look.
