### ISSUE TITLE
DRF addition break integration with Django Simple Captcha

### ISSUE THREAD

**Issue by jeroenmaas** [jazzband/django-axes#666]
Since https://github.com/jazzband/django-axes/commit/ae49f3bdae26b9404f83cd7023f3cb39b8b75278 the integration with Django Simple Captcha broken. This forces me to stay on 3.7.x for now. 

I have project that contains DRF for certain urls but also contains "normal" django requests. When the lockout is triggered the user is redirected to /locked and normally they see the captcha, but now this piece of code is activated and is detected that a lockout has occured, redirecting the user to /locked even though that is the page we are currently at! Causing a infinite loop.

**Comment by aleksihakli** [comment]
Hey @jeroenmaas! The simplest way to implement support would be to add your own middleware class that supports your particular setup.

**Comment by jeroenmaas** [comment]
Thank you for the reply @aleksihakli. Guess my use case is a bit special. I'll make my own middleware class that reverts the mentioned commit.
