### ISSUE TITLE
Avoid reinitilizing AXES_COOLOFF_TIME for repeat attempts

### ISSUE THREAD

**Issue by yahyadev69** [jazzband/django-axes#667]
I integrated django-axes to my django application whith the following configs :

15 minutes (as timedelta object for minutes)
AXES_COOLOFF_TIME = timedelta(minutes=15)

Here are the spteps :

1 - I tried 3 time to connect with correct user and wrongs password --> result : the user is locked out (i see the messsage : user locked out during 15 min) 

2 - after 10 minutes, i try again to connect with correct user and password
--> result : the user is locked out again and have to wait another 15 minites ! in total i lost 25 mintes waiting instead to 15 !

Is there a way to avoid this probleme ? I want to use the first duration and not account the second.

Appreciate you help

**Comment by hramezani** [comment]
When the user is locked, every login attempt considered to be a failed login, and every failed login update the `attempt_time` for the locked account. So, `AXES_COOLOFF_TIME` will be calculated after the last attempt time(Whether successful or unsuccessful)

**Comment by aleksihakli** [comment]
Well, it's possible to implement a check for only updating the cool off time if it is not valid anymore, but do you think this should be part of the default behaviour?

**Comment by jachane99** [comment]
On the topics of cooloff time, I'm looking to implement django axes for brute force protection for my application. I want to implement something like this "lockout for 5 minutes after 5 failed attempts, lockout for 10 minutes after another 5 attempts" Seems like the example in the doc is more straightforward with a fixed wait time, so I want to know if it's possible to implement something like this.

**Comment by aleksihakli** [comment]
The incrementing or growing wait time is not supported at the moment, I think, so it would have to be a new feature. The project is open for contributions if you would be interested in making this available for everyone.

**Comment by jachane99** [comment]
Regarding the previous comment, do you have suggestions on how to implement a check for only updating the cool off time? Would it be appropriate to override the `DatabaseDefaultHandler` to update the record while valid?

**Comment by aleksihakli** [comment]
The cool off time is static at the moment, but if you wanted to make it more dynamic, you would have to indeed specialize the database handler for your needs, if you are using the database for tracking failures in your project. At the moment the tracking is done with static attempt time update and a timedelta calculation from there, so you would have to e.g. skip updating the attempt time with certain conditions:

https://github.com/jazzband/django-axes/blob/2d228ea49bea91900b9f94c36d839ed454d17ea5/axes/handlers/database.py#L148
