### ISSUE TITLE
Extra database requests always made with DRF integration

### ISSUE THREAD

**Issue by Jenselme** [jazzband/django-axes#673]
Hi,

I experienced issues with one extra database query in my tests suite after the update to version 5.8.0. The request is:
```sql
SELECT SUM("axes_accessattempt"."failures_since_start") AS "failures_since_start__sum"
FROM "axes_accessattempt"
WHERE ("axes_accessattempt"."ip_address" = '127.0.0.1'::inet AND "axes_accessattempt"."username" IS NULL AND "axes_accessattempt"."attempt_time" >= '2020-11-03T14:32:57.279609+00:00'::timestamptz)
```

I did some digging and it seems to come from the work done in #659 to fix integration with DRF. From what I understand, we normally just track the login attempts when a user fail to login with `user_login_failed`. So, unless we are on a login view, no extra database requests are made. However, with this update, we always do one extra request, even if we are not on a login view (a plain `ListView` in may case) because of the call to `get_failure_limit` which is always done in the middleware.

Is this the desired behavior?

**Comment by aleksihakli** [comment]
Good catch @Jenselme!

The behaviour should probably be so that Axes only checks the information on login views, reducing extra database load from normal, unrelated requests.

What do you think would be the best way to realize this?

**Comment by Jenselme** [comment]
> What do you think would be the best way to realize this?

Would it make more sense to move this code out of the middleware to handle DRF in https://github.com/jazzband/django-axes/blob/22c564743db7c2abf3051e6ba10ec28fdb70b027/axes/handlers/database.py#L86?

**Comment by aleksihakli** [comment]
I think the problem relates to this https://github.com/jazzband/django-axes/issues/570#issuecomment-709292733. The handler gets the wrapped request, the middleware gets the original request.

One valid option would be to check if the view is an authentication view, but I'm not sure where that information would be available from.

**Comment by Jenselme** [comment]
Do you mean implementing something like this in the middleware:
```python
    def __call__(self, request):
        if "rest_framework" in settings.INSTALLED_APPS:
            def deny_access(**kwargs):
                raise PermissionDenied('Too many failed login attempts')

            user_locked_out.connect(deny_access)

        response = self.get_response(request)
```
As suggested in https://github.com/jazzband/django-axes/issues/570#issuecomment-708713546?

I confess I don't know much about signals yet.

**Comment by pzelnip** [comment]
One way in which this issue has bitten us is now some tests that inherited from `SimpleTestCase` now require inheriting from `TestCase`.

Similarly some pytest-style function tests that previously didn't require DB access now require the `@pytest.mark.django_db` annotation to pass.

**Comment by aleksihakli** [comment]
@pzelnip have you tried setting by configuring `AXES_ENABLED = False` in your test settings?

**Comment by Jenselme** [comment]
@aleksihakli It can solve the issue for tests, but in proluction we will still do SQL requests we don't need. Which is my main concern.

**Comment by Jenselme** [comment]
@aleksihakli nice PR by the way. I'll try to test that by the end of the week.

**Comment by pzelnip** [comment]
> @pzelnip have you tried setting by configuring `AXES_ENABLED = False` in your test settings?

I have not, but I'll give that a try, good tip!
