### ISSUE TITLE
Infinite redirects with DRF integration

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [jazzband/django-axes#682]
Same issue as #676, but there wasn't any reproductive case and there wasn't any response. To reproduce the error:

If you follow the documentation for Simple Captcha (I'm using recaptcha, but it acts the same way) here: https://django-axes.readthedocs.io/en/latest/6_integration.html#integration-with-django-simple-captcha, you will get too many redirects (status code 302) with if DRF is enabled. If you remove it from `INSTALLED_APPS`, the template loads.

If you would like an immediate test, visit https://github.com/Donate-Anything/Donate-Anything. Add DRF as a dependency, add it to INSTALLED_APPS, then build via Docker. Turn on and off `rest_framework` in the `INSTALLED_APPS, and you'll find find the redirects.

---

Even without this, if you enable AXES_LOGOUT_URL with DRF enabled, you'l get too many redirects.

**Comment by sobolevn** [comment]
Yes, I confirm. Sadly, I cannot provide a reproduction.

**Comment by sobolevn** [comment]
Falling back to `5.7` saves the day.

**Comment by aleksihakli** [comment]
Thanks for the additional data. I'm a bit short on time so if anyone has the ability to track down this error that would be very helpful.

**Comment by aleksihakli** [comment]
#689 might prove helpful. Could you test if disabling middleware and using the signals approach in the PR works on your environment with DRF and Django Simple Captcha?

**Comment by Andrew-Chen-Wang** [comment]
I just finished my finals, so I should have time tomorrow to test out your PR. But since I'm done with finals, I also want to see if I can trace back how this circular loop even happens... (to clarify, I was using recaptcha, but even disabling recaptcha didn't work).

**Comment by sobolevn** [comment]
For me it happened right in the https://github.com/jazzband/django-axes/blob/9acf904568c9cf973bbd2e358a04fec693c7acea/axes/middleware.py#L46-L61 part

**Comment by aleksihakli** [comment]
This should be resolved in version 5.10.0.

Please note that the implementation has changed and DRF is not supported with stock Axes implementation, and needs signals. Refer to the documentation for examples on this:

https://django-axes.readthedocs.io/en/latest/6_integration.html#integration-with-django-rest-framework

**Comment by aleksihakli** [comment]
Could somebody test the version with their DRF stack and see how it works?
