### ISSUE TITLE
Returned more than one AccessAttempt

### ISSUE THREAD

**Issue by maresp85** [jazzband/django-axes#683]
AccessAttempt.MultipleObjectsReturned: get() returned more than one AccessAttempt -- it returned 2!

```
  File "axes/handlers/database.py", line 125, in user_login_failed
    attempt = AccessAttempt.objects.get(
```

**Comment by hramezani** [comment]
Hi @maresp85, Could you please explain more.

- Python version
- Django version
- django-axes version

How do you get this error?

**Comment by maresp85** [comment]
Hi, 

Python version 3.8
Django version 3.1.2
django-axes version 5.8.0

**axes/handlers/database.py in user_login_failed at line 125**

        # 3. database query: Insert or update access records with the new failure data
        try:
            attempt = AccessAttempt.objects.get(
                username=username,
                ip_address=request.axes_ip_address,
                user_agent=request.axes_user_agent,
            )

**Comment by hramezani** [comment]
We need some clear steps to reproduce the problem.

**Comment by aleksihakli** [comment]
What database and other Axes configuration are you using?

**Comment by aleksihakli** [comment]
Closing the issue as no further information has been reported regarding this issue.
