### ISSUE TITLE
No flexibility for get_client_parameters (AXES_LOCK_OUT_BY_COMBINATION_USER_AGENT_AND_IP, AXES_LOCK_OUT_BY_COMBINATION_USER_AGENT_AND_USER and AXES_LOCK_OUT_BY_USER_AGENT_ONLY options needed)

### ISSUE THREAD

**Issue by instantrad** [jazzband/django-axes#690]
We realised with below config; Every user on our website gets locked out. 
AXES_FAILURE_LIMIT = 2
AXES_LOCK_OUT_AT_FAILURE = True
ONLY_USER_FAILURES = False
AXES_USE_USER_AGENT = True
AXES_COOLOFF_TIME = timedelta(minutes=15)

The issue is that the **filter_query** filter out the ip or user_agent. This means that all users with **same IP** but different **user agents** get locked out.

**PROPOSAL:**

```def get_client_parameters(username: str, ip_address: str, user_agent: str) -> list:
    if settings.AXES_ONLY_USER_FAILURES:
        filter_query = [{"username": username}]
    else:
        if settings.AXES_LOCK_OUT_BY_USER_OR_IP:
            filter_query = [{"username": username}, {"ip_address": ip_address}]
        elif settings.AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP:
            filter_query = [{"username": username, "ip_address": ip_address}]
        elif settings.AXES_LOCK_OUT_BY_COMBINATION_USER_AGENT_AND_IP:
            filter_query = [{"user_agent": user_agent, "ip_address": ip_address}]
        elif settings.AXES_LOCK_OUT_BY_COMBINATION_USER_AGENT_AND_USER:
            filter_query = [{"user_agent": user_agent, "username": username}]
        elif settings.AXES_LOCK_OUT_BY_USER_AGENT_ONLY:
            filter_query = [{"user_agent": user_agent}]
        else:
            filter_query = [{"ip_address": ip_address}]
    return filter_query```

**Comment by aleksihakli** [comment]
I have a wish of cleaning up the flags and just supplying users the option of configuring the filter parameters that should be in the query themselves by keywords for example. 

Something like:

    # settings.py
    AXES_LOCKOUT = ["ip_address"]

Then just check that configuration on startup and maybe even allow users to supply their own custom method of resolving the lockout parameters from the request.

Would it make sense to refactor the whole implementation? It's messy and has layers of legacy to be honest.

**Comment by instantrad** [comment]
Your suggestions will work better considering the legacy code you mentioned. That will also provide the flexibility needed

**Comment by aleksihakli** [comment]
@instantrad a PR has been merged and is about to be released as part of version 6, do you want to take a look pre-release?
