### ISSUE TITLE
Refactor client lockout parameter resolution

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#692]
Opening public discussion on feature request for redesigning and refactoring the lockout parameter resolution functionality as per discussion in jazzband/django-axes#690

Proposal: use a new flag such as `AXES_LOCK_OUT_PARAMETERS` which accepts an iterable of keys or a callable that resolves an iterable. Use a sane default value with behaviour similar to that of current defaults. Make a new major release version 6 release that deprecates the old lock out parametrization. Also go through other flags that could be cleaned up?

Example:

```
# settings.py
# this could also be a callable that takes request and credentials as parameters?
AXES_LOCKOUT_PARAMETERS = ["ip_address"]
```

Deprecate or clean up the following flags ([reference](https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-project-settings)):

- AXES_USE_USER_AGENT
- AXES_LOCK_OUT_AT_FAILURE
- AXES_LOCK_OUT_BY_USER_OR_IP
- AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP

**Comment by hirotasoshu** [comment]
@aleksihakli I'm wondering about something like this
```python
AXES_LOCKOUT_PARAMETERS = [
    "ip_address",
    ("username", "user_agent"),
]
```
this parameters will produce filter_query like this:
```python
filter_query = [{"ip_address": ip_address}, {"username": username, "user_agent": user_agent}]

**Comment by aleksihakli** [comment]
Yeah that actually sounds like a good idea. I was wondering of different implementation options and

1. iterable, or
2. a callable that produces an iterable

that you proposed would be "design compatible" with the current implementation and feature set.

Another option would be to simplify the lockout resolution to only use one list of combined attributes, but that would reduce the scope of the lockouts and be incompatible with the current implementation.

**Comment by aleksihakli** [comment]
> @aleksihakli I'm wondering about something like this
> 
> ```python
> AXES_LOCKOUT_PARAMETERS = [
>     "ip_address",
>     ("username", "user_agent"),
> ]
> ```

Would you happen to have the opportunity of baking a PR out of this proposal @hirotasoshu?

**Comment by hirotasoshu** [comment]
@aleksihakli I'm already working on that, the problem is that I don't have a lot of free time right now

**Comment by aleksihakli** [comment]
That sounds good! Thanks for the effort and assigning the story. There's no hurry, I just thought to ask for sake of better coordination 👍

I think your proposed change format would be an excellent fit for the version 6.x release later on, and would be nice to include in addition to the current pre-release updates for better deprecation notices and upgrade instructions for `django-axes` package users.
