### ISSUE TITLE
Version 6.0.0 release

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/django-axes#693]
The goal for the next major version 6 is to produce an improved version of Axes where the functionality and configuration is more consistent and documentation has more examples of configuring the project to suit individual project scenarios.

This issue will track larger design points and deprecating functionality as a whole and act as an entrypoint for people wanting to participate in the version 6 design, development, testing, and release process.

There is no official timeline or feature set agreed upon as of yet, the project is open for participation and discussion.

Larger features that will cause deprecation in settings and APIs and require the major semantic versioning bump to 6.x include.

- Improvement of HTTP status codes based on #570
- Improvement of sensitive data processing based on #663
- Redesign of lockout parameter resolution based on #690 and #692

**Comment by aleksihakli** [comment]
Hey @hirotasoshu, do you happen to have thoughts on what to include in the initial `6.0.0` release?

I would kind of want to see #690 and #692 as part of the breaking release as they have been on the backlog for quite some time, any thoughts on those? I think specifying either a callable or a list of arguments to take into account would be a good approach?

**Comment by aleksihakli** [comment]
All related issues and proposals are merged. The next would be to check the current docs and instructions, bake release notes, and write upgrade instructions in the docs for anyone updating from version 5.x to 6.x. Are there any other blockers for making the release after that?

**Comment by hirotasoshu** [comment]
@aleksihakli I think we should also include #772 to new release. Since we already deprecate a lot of old stuff, deprecate `is_admin_site` will look harmonious in a major release

**Comment by aleksihakli** [comment]
Agreed. I don't have time to update the implementations myself any time soon but would you or anyone else happen to have the chance of making a PR for that?

**Comment by aleksihakli** [comment]
We should make release notes and upgrade instructions for people who wish to use Axes and keep the same behaviour as they had in the previous release. 

After that I think we could roll out version 6.0.0 as a latest stable release?

The RTD documentation and changelog could perhaps be a good place to include the instructions in.

**Comment by aleksihakli** [comment]
Version 6.0 has been completed and released into PyPI along with patch 6.0.1 which includes fixes to CI and RTD configurations 🎉 

This issue can still be used to report any issues with the latest release you may encounter, or you can open separate issues and PRs as you see best.
