### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tobeyforce** [jazzband/django-axes#715]
I'm having issues integrating Django axes with DRF using djoser as an auth backend, which I believe is among the more common solutions in DRF.
Registering and keeping track of logins works great, but the lockout errors are painful.

In my views.py tried overriding the Djoser token create method in order to add the decorator.
```
@method_decorator(axes_dispatch, name='dispatch')
class DjangoAxesTokenCreateView(TokenCreateView):
    from . import signals
    pass
```
In urls:
`url(r"^auth/token/login/?", views.DjangoAxesTokenCreateView.as_view(), name="token-create"),`
Again, this does indeed work, but the response from being locked out is in HTML.
So I tried adding a signal as instructed in the docs:
```
 @receiver(user_locked_out)
 def raise_permission_denied(*args, **kwargs):
     raise PermissionDenied("Too many failed login attempts")
```

This result in a JSON-response the first time the blocking is done, however on any consecutive responses it returns to being HTML. So instead, I tried using the LOCKOUT_TEMPLATE in settings.py, however this also only returns HTML.

So... im either:
1. Wondering if you could add a JSON-option to the lockout-template, so that it returns it as a JSON-response.
2. Wondering how I can make sure the error triggered by the signal is run on every consecutive login fail after the first
3. Other solution?

I realize this is a mix of asking for help & feature requests, my apologies.

Edit: 
As a workaround I used the redirect AXES_LOCKOUT_URL to return a custom response for it.

**Comment by aleksihakli** [comment]
Hi @Tobeyforce!

Have you checked the `settings.AXES_LOCKOUT_CALLABLE` method? You can configure a custom function for returning the lockout response.

- https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuring-project-settings
- https://github.com/jazzband/django-axes/blob/master/axes/helpers.py#L316

You shouldn't import signals in your class definition, that should be done on the application level in your `apps.py` in `.ready()`:

- https://docs.djangoproject.com/en/3.1/ref/applications/#django.apps.AppConfig.ready

**Comment by Tobeyforce** [comment]
Hi,
Thanks for taking your time.
I'll try to look into it! That seems like what I need.

**Comment by aleksihakli** [comment]
An example of usage could be e.g. a custom view for processing lockouts:

```python
# example/views.py

from django.http import JsonResponse

def lockout(request, credentials, *args, **kwargs):
    return JsonResponse({"status": "Locked out due to too many login failures"}, status=403)
```

And custom setting pointing to the lockout callable:

```python
# settings.py

AXES_LOCKOUT_CALLABLE = "example.views.lockout"
```

**Comment by Tobeyforce** [comment]
Excellent, you even went ahead and did it for me ;-)
That pretty much answers my question on this topic, hope others will find it if they encounter the same issue. Thanks!

**Comment by aleksihakli** [comment]
I renamed the issue so it's a bit easier to find via search engine :) Probably good to add this to docs as well.

**Comment by Tobeyforce** [comment]
Makes sense, yes that would be great as I can really see this being a common problem people encounter since DRF Is growing :-)
