### ISSUE TITLE
Would HTTP 429s be more appropriate?

### ISSUE THREAD

**Issue by anthonyryan1** [jazzband/django-axes#728]
I recently had a penetration tester question whether or not django-axes was working because it returned the same 403 code as an invalid password attempt.

I did verify it was working correctly, but I thought I would raise the issue for discussion on whether there would be merit to using a 429 status code instead of a 403.

The 429 is arguably more semantically correct than the 403, and would make it easier to distinguish a rejected password vs a blocked attempt via HTTP headers alone.

I look forward to your thoughts. If you feel this is a worthwhile change I can prepare a pull request.

**Comment by aleksihakli** [comment]
HTTP 429 might be semantically more correct:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

The response could also in principle include the standardized `Retry-After` header to indicate how long the lockout period is.

This would change the current behaviour and be a good candidate for the version 6 release of Axes?

**Comment by aleksihakli** [comment]
@anthonyryan1 this has now been made possible by #770 but I'm wondering if the default could still perhaps be updated from 403 to 429, and would this warrant a major release 6.x as part of the update?
