### ISSUE TITLE
rate limiting of login attempts

### ISSUE THREAD

**Issue by BoPeng** [jazzband/django-axes#730]
[django-ratelimit-backend](https://github.com/brutasse/django-ratelimit-backend) appears to be useful but I am not sure if it works with my allauth + axes configuration. Has anyone tried to make these three work together? It might also makes sense to add rate limiting to django-axes since axes is already keeping track of login attempts.

**Comment by aleksihakli** [comment]
Looking at the ratelimiter repo the last commits are from a few years ago from May 2019, is the project supported?

One note on ratelimiting is that there are tools for reverse proxy and load balancer based rate limiting. I would recommend checking out the fail2ban project for references.

**Comment by BoPeng** [comment]
Thanks for your comments. `fail2ban` indeed could be a better option although I would prefer a django solution since it is more straightforward to deploy. I will close this ticket for now.

**Comment by aleksihakli** [comment]
If you do find a good solution or have any notes we appreciate any insight for e.g. updating the docs regarding good rate limiting solutions for Django :)

**Comment by BoPeng** [comment]
Another candidate app along the defense line of my django deployment would be [`django-admin-honeypot`](https://github.com/dmpayton/django-admin-honeypot), which I again hesitate to add due to compatibility and duplicate tracking issues.

I am not advocating for `axes` to steal the idea of these apps but it would be nice for `axes` to become the swissknife of such apps with an integrated tracking and defense system.

**Comment by aleksihakli** [comment]
I've also though about the different applications that try and monitor authentication and rate limiting for Django but I think that it would be best to keep the implementation and code for Axes as-simple-as-possible for maintainability and separation of concerns. Note that these are just my personal thoughts and philosophy on the implementation and this package is maintained by Jazzband, so if you think that this is something that would be useful, please feel free to open an issue or pull request for drafting a specification or implementation for the issue.
