### ISSUE TITLE
Feature request: extensible get_client_str

### ISSUE THREAD

**Issue by charleswhchan** [jazzband/django-axes#739]
We would like the ability to customize the message returned by get_client_str() and decorate the output and redact certain private information. Rather than building a full backend, can a new customization be added similar to examples listed in https://django-axes.readthedocs.io/en/latest/4_configuration.html#configuration?

**Comment by aleksihakli** [comment]
Hi @charleswhchan! Sure, you can add a configuration flag for defining the callable and then add a configuration value for that, similar to the ones that are already implemented. Would you be interested in opening a PR for this? Please include the implementation, docs, and unit tests for the configuration flag in the same PR. They should be fairly easy to add by using the existing implementations as examples.

**Comment by aleksihakli** [comment]
Hey @charleswhchan and @smtydn, this should be available in 5.16.0 soon :)

**Comment by charleswhchan** [comment]
Thank you so much!! @aleksihakli @smtydn
