### ISSUE TITLE
Seperate log from access attempts

### ISSUE THREAD

**Issue by stephenlutes** [jazzband/django-axes#768]
If there is a feature I am missing, great, but if not, is there any plan to separate the log from access attempts. Essentially, I want to enable the cooloff time, but I still want to be able to see the failed attempts after that. Currently, to unlock an account, you have to remove the log of failed attempts.

**Comment by aleksihakli** [comment]
Hey @stephenlutes! There is a model for access logging but I don't think it is currently used:

https://github.com/jazzband/django-axes/search?q=accesslog

Have you considered using logging itself and storing the attempts in a separate write-only log storage for auditing and reviewing attempts? Storing logs in the same storage (Django database) that can be later modified by the logging system (Django) can be a security concern, if a malicious actor is able to mutate the contents of the logs after gaining access to a system.

**Comment by stephenlutes** [comment]
I hadn't considered storing it in logs (though I should have). However, I still have a use case where just logging it still doesn't solve the issue. If the user is allowed to see past history, but also be presented the option to clear that history. Maybe this is something I should just put in a separate app and extend the current one, but it is a use case I see either way.

**Comment by aleksihakli** [comment]
In that case it would probably be useful to extend the logging so that AccessLog records are created as well.

One option would be to also include that logic in Axes with a flag, so that the attempts would be created when toggled on?
