### ISSUE TITLE
"is_admin_site" has the opposite meaning

### ISSUE THREAD

**Issue by okapies** [jazzband/django-axes#772]
`AxesHandler.is_admin_site()` actually checks if a `request.path` is *NOT* located under the `reverse("admin:index")`.

https://github.com/jazzband/django-axes/blob/ea4d3c477dd1fda2045ed8c927b6d0bb87200d27/axes/handlers/base.py#L136-L147

**Comment by hramezani** [comment]
Yeah, I agree the name is not good.
`is_admin_site` returns `True` if `AXES_ONLY_ADMIN_SITE` is enable and the request path located under admin site.
do you have any suggestions for the function name?

**Comment by okapies** [comment]
How about the following?

```python
def is_allowed(self, request, credentials: dict = None) -> bool:
    ...
    if settings.AXES_ONLY_ADMIN_SITE and self.is_admin_request(request):
        return True
    ...

def is_admin_request(self, request) -> bool:
    if hasattr(request, "path"):
        return not is_admin_site(request)
    else:
        return False

def is_admin_site(self, request) -> bool:
    """Deprecated. Use `is_admin_request` instead."""
    ...
```

**Comment by hramezani** [comment]
@aleksihakli what do you think about the new naming?

**Comment by aleksihakli** [comment]
The naming is misleading. If you think there would be a better naming convention or logic for the function, then I'd vouch for fixing both the semantics for naming and functionality, as that would make the code easier to read and maintain in the long run? If we just add a method and mark another one deprecated then that doesn't really solve the issue of the implementation not being clear as-is.

**Comment by okapies** [comment]
Agreed. I'm just worried that someone uses `is_admin_site` for their custom handler. I also think the logic depends on `settings` should be placed at `is_allowed` if you can fix all `is_*`s.

**Comment by aleksihakli** [comment]
I think it's OK to just introduce a new method with a better name and deprecate the old method either with a DeprecationWarning or just remove it so that anyone utilizing it would get a warning or an error from using it?

**Comment by aleksihakli** [comment]
@okapies we're baking a new version 6.x release, would you be interested in including this change in that release? Now would be a good time to make breaking improvements and changes to the code base if you have any improvements in mind :)
