### ISSUE TITLE
[Feature Request] Pass User object to AXES_CLIENT_STR_CALLABLE

### ISSUE THREAD

**Issue by roniemartinez** [jazzband/django-axes#782]
Use case: We want to include more info about the user in the client_str.

`username` is already included in the arguments but that would require us to do a separate DB call which is not very efficient.

**Comment by aleksihakli** [comment]
Hey @roniemartinez! Would you like to open a PR for implementing this functionality?

**Comment by aleksihakli** [comment]
Closed by #783 

Released in 5.23.0 @roniemartinez
