### ISSUE TITLE
Whitelist URLs / Working with OAuthtoolkit

### ISSUE THREAD

**Issue by ZuSe** [jazzband/django-axes#786]
Hi folks,

i checked the docs but didnt find an answer to my question.
Would it be possible to whitelist serveral URLs of my applications?

In our case, we are using axes together with the oauthtoolkit and resource server, which do from time to time calls against the userinfo endpoint of oidc. 
However, in case a client provided an expired token the resource server would receive a 403 from the oauth provider.
Axes would count that as a failure attempt and log the IP of the resource server. So after some time, the IPs of my resource servers get locked - which I want to prevent.

For that I would like to take all requests against oidc/userinfo/ from axes. 

Best
Patrick

**Comment by aleksihakli** [comment]
Have you looked into `settings.AXES_WHITELIST_CALLABLE`?

- https://django-axes.readthedocs.io/en/latest/4_configuration.html
- https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpRequest.path

It could be written e.g. like:

```python
def is_whilisted(request, *args, **kwargs):
    return request.path.lower().startswith('/oidc/endpoint/url')
```

**Comment by ZuSe** [comment]
Thanks, that helped a lot.
I looked at the config but didnt see the variable :)
