### ISSUE TITLE
Axes user IP is not set for private proxy IPs

### ISSUE THREAD

**Issue by supermario18b** [jazzband/django-axes#813]
Hi,

I use a nginx reverse proxy server in front of my django app. In my location block I have these settings:

`proxy_set_header X-Real-IP $remote_addr;`
 `proxy_set_ X-Forwarded-For $proxy_add_x_forwarded_for;`

and in Django settings.py I have:

`AXES_PROXY_COUNT = 1`
`AXES_META_PRECEDENCE_ORDER = ( 'HTTP_X_REAL_IP','HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', )`

Unfortunately the caught ip from axes is "None".

I'm quite sure that the request.META["HTTP_X_FORWARDED_FOR"] and request.META["HTTP_X_REAL_IP"] are set because I use them with a signal for creating a model object.

Could you please help me to understand what I'm doing wrong? Is there a way to enable a debug mode?

Thanks in Advance,

supermario18b

**Comment by supermario18b** [comment]
I don't know if it is relevant, but I forgot to say that at the moment are local addresses (192.168.) since I'm still developing the app.

**Comment by supermario18b** [comment]
After reading the code of django-ipware I think that the normal behaviour is to return None if the IPs are not public routable.
It should work when I'll let nginx listen on the public interface (internet).

**Comment by aleksihakli** [comment]
Hey @supermario18b, did you figure out what was causing the issue?

**Comment by aleksihakli** [comment]
Hi @supermario18b, did you get this working in your implementation?

**Comment by supermario18b** [comment]
> Hi @supermario18b, did you get this working in your implementation?

Hi, actually I'm still developing the app and the nginx proxy still has a not public routable ip (192.168.).
The proxy is reached only by the lan.

As I wrote,  since the normal behaviour of django-ipware is to return None if the IPs are not public routable (lan),  I think axes will show the ip when I'll deploy to a server with a public ip.

Since Axes uses Ipware, I think Axes is working fine.

**Comment by aleksihakli** [comment]
OK, good to hear! I've updated the PR title to reflect the technical state of things, I think it would be great to get this documented in the repository docs which are uploaded to RTD. 

If somebody would be interested in opening a PR for updating the docs that would be great :)

**Comment by krishdb38** [comment]
I am facing almost the same situation.
I am getting user IP if SSL is not activated.
if I use SSL in Nginx then instead IP only - is recording.

does anyone know how to solve this issue while deployed with gunicorn, Nginx, & SSL?

**Comment by krishdb38** [comment]
location / {
        proxy_pass                   http://mysite.net;
        proxy_set_header            Host $host;
        proxy_set_header            X-Real-IP $remote_addr;
        proxy_http_version          1.1;

        proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header            X-Forwarded-Proto http;
        proxy_redirect              http:// $scheme://;
    }
}

## i am getting ip addres by changing config file like this way
