### ISSUE TITLE
Failed logins and attempt time updated even when lockedout

### ISSUE THREAD

**Issue by igonro** [jazzband/django-axes#837]
I'm not sure if this is intended or not, didn't find any information in the docs related to this.

The problem is that is an user is lockedout, the failed logins and the attempt time gets updated. This way `AXES_COOLOFF_TIME` is not working as expected, or at least as I would expect.

Example with `AXES_COOLOFF_TIME=1` (hour):
- Current behaviour
1. User fails to login 3 times, the last attempt at 10:05.
2. User gets lockedout until 11:05.
3. User tries to login at 10:50, and failed logins updates to 4, and attempt time updates to 10:50, so the user will be lockedout until 11:50. Also this is true even if the 4th attempt was with the right credentials.

- Expected behaviour
1. User fails to login 3 times, the last attempt at 10:05.
2. User gets lockedout until 11:05.
3. User tries to login at 10:50, the user will not login to the site even with the right credentials, but the attempt will NOT be taken into account.

I think this should be the typical behaviour, because the user probably won't know the exact time of the last failed login, maybe he thinks that the last attempt was at 10:00, and he tries to access at 11:01, but then he will see that now he is going to be lockedout 1 more hour, even if he tried with the right credentials. The current behaviour leads us to a scenario where an user could be lockedout easily for 2 or 3 hours, if he tries to access before the correct time, instead of the intended `AXES_COOLOFF_TIME` of 1 hour.

I hope I explained correctly. Thanks for your time!

**Comment by aleksihakli** [comment]
Hi @igonro, and thanks for filing the issue!

This does seem to be a limitation of the current implementation, and would require changes in the code logic to update. Would you be interested in researching or lining out the necessary changes to update the behaviour of the code to match the expected outcome?
