### ISSUE TITLE
Add failed login history for ever, not just until good login, to allow listing them in a view

### ISSUE THREAD

**Issue by p1-gdd** [jazzband/django-axes#863]
I provide the PR #862 to allow access to ALL failure logins.

**Comment by draizu** [comment]
add for model translate Access failures, please

**Comment by p1-gdd** [comment]
Can you be more explicit please?

**Comment by aleksihakli** [comment]
Are you possibly referring to Django translations?

https://docs.djangoproject.com/en/dev/topics/i18n/translation/
