### ISSUE TITLE
Missing German translation for "Access failures"

### ISSUE THREAD

**Issue by GitRon** [jazzband/django-axes#892]
I just realised that this translation is missing. I'd go with something like "Fehlgeschlagene Zugriffsversuche" (plural) and "Fehlgeschlagener Zugriffsversuch" (singular)

Best  
Ronny

**Comment by aleksihakli** [comment]
Hi @GitRon and thanks for reporting the issue. The proposal sounds good, would you like to a open a PR for it?

**Comment by GitRon** [comment]
@aleksihakli I created a PR 😃

**Comment by aleksihakli** [comment]
Released as part of version 5.34.0.
