### ISSUE TITLE
W003 error in 5.36.0 using AxesStandaloneBackend

### ISSUE THREAD

**Issue by oscarsiles** [jazzband/django-axes#907]
Upon upgrading to the latest version, and switching to AxesStandaloneBackend under AUTHENTICATION_BACKENDS, I am getting the W003 error. I've silenced it for now using the info in the docs, but perhaps the config checker needs updating as well?

**Comment by simonkern** [comment]
confirmed - I got the same warning, after following the instructions in the documentation.

**Comment by aleksihakli** [comment]
Released to PyPI in version 5.39.0.
