### ISSUE TITLE
cannot import name ugettext_lazy from django.utils.translation django-axes

### ISSUE THREAD

**Issue by sandeepkmr088** [jazzband/django-axes#985]
Django==4.0.2
django-axes==5.40.1

![error](https://user-images.githubusercontent.com/20681021/212466820-b12f7224-2bd3-4b88-8e86-39c1c763ec89.jpg)

**Comment by keyvanmj** [comment]
It was removed from Django 4, use this instead
### use this :
    from django.utils.translation import gettext_lazy as _
